/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class telaLogin extends javax.swing.JFrame {

    /**
     * Creates new form telaLogin
     */
    public telaLogin() {
        initComponents();
        
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/ceetecaicon16x16.png"));
        this.setIconImage(icone.getImage());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTelaLogin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cTxtSenhaTelaLogin = new javax.swing.JPasswordField();
        cTxtUsuarioTelaLogin = new javax.swing.JTextField();
        btEntrarTelaLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CEETECA");
        setResizable(false);

        painelTelaLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                painelTelaLoginKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Usuário:");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Senha:");

        cTxtSenhaTelaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTxtSenhaTelaLoginActionPerformed(evt);
            }
        });
        cTxtSenhaTelaLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cTxtSenhaTelaLoginKeyPressed(evt);
            }
        });

        cTxtUsuarioTelaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTxtUsuarioTelaLoginActionPerformed(evt);
            }
        });
        cTxtUsuarioTelaLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cTxtUsuarioTelaLoginKeyPressed(evt);
            }
        });

        btEntrarTelaLogin.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btEntrarTelaLogin.setText("Entrar");
        btEntrarTelaLogin.setToolTipText("");
        btEntrarTelaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarTelaLoginActionPerformed(evt);
            }
        });
        btEntrarTelaLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btEntrarTelaLoginKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout painelTelaLoginLayout = new javax.swing.GroupLayout(painelTelaLogin);
        painelTelaLogin.setLayout(painelTelaLoginLayout);
        painelTelaLoginLayout.setHorizontalGroup(
            painelTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelaLoginLayout.createSequentialGroup()
                .addGroup(painelTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTelaLoginLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cTxtUsuarioTelaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                    .addGroup(painelTelaLoginLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cTxtSenhaTelaLogin)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTelaLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btEntrarTelaLogin)
                .addGap(122, 122, 122))
        );
        painelTelaLoginLayout.setVerticalGroup(
            painelTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelaLoginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(painelTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cTxtUsuarioTelaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(painelTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cTxtSenhaTelaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btEntrarTelaLogin)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/100x50.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTelaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelTelaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cTxtUsuarioTelaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTxtUsuarioTelaLoginActionPerformed
        // 


    }//GEN-LAST:event_cTxtUsuarioTelaLoginActionPerformed

    private void cTxtSenhaTelaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTxtSenhaTelaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTxtSenhaTelaLoginActionPerformed

    /*public void butEntrar(KeyEvent butEnter) {
        
        if (butEnter.getKeyCode() == KeyEvent.VK_ENTER) {
            
            JOptionPane.showMessageDialog(null, "Acesso permitido");
            
        }
    }*/

    private void btEntrarTelaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarTelaLoginActionPerformed

    }//GEN-LAST:event_btEntrarTelaLoginActionPerformed

    private void btEntrarTelaLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btEntrarTelaLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (cTxtUsuarioTelaLogin.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Está faltando o usuario!");
            } else if (cTxtSenhaTelaLogin.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Está faltando a senha!");
            } else if (!cTxtUsuarioTelaLogin.getText().equals("root")) {
                JOptionPane.showMessageDialog(null, "O usuario está incorreto!");
            } else if (!cTxtSenhaTelaLogin.getText().equals("1234")) {
                JOptionPane.showMessageDialog(null, "A senha está incorreta!");
            } else if (cTxtUsuarioTelaLogin.getText().equals("root") && cTxtSenhaTelaLogin.getText().equals("1234")) {
                JOptionPane.showMessageDialog(null, "Acesso Permitido!");
                TelaPrincipal tela = new TelaPrincipal();
                //Deixa uma janela visível(true), ou invisível(false)        
                tela.setVisible(true);
                //Fecha a janela para poder exibir a próxima
                dispose();
            }
        }
    }//GEN-LAST:event_btEntrarTelaLoginKeyPressed

    private void painelTelaLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_painelTelaLoginKeyPressed

    }//GEN-LAST:event_painelTelaLoginKeyPressed

    private void cTxtSenhaTelaLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtSenhaTelaLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (cTxtUsuarioTelaLogin.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Está faltando o usuario!");
            } else if (cTxtSenhaTelaLogin.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Está faltando a senha!");
            } else if (!cTxtUsuarioTelaLogin.getText().equals("root")) {
                JOptionPane.showMessageDialog(null, "O usuario está incorreto!");
            } else if (!cTxtSenhaTelaLogin.getText().equals("1234")) {
                JOptionPane.showMessageDialog(null, "A senha está incorreta!");
            } else if (cTxtUsuarioTelaLogin.getText().equals("root") && cTxtSenhaTelaLogin.getText().equals("1234")) {
                JOptionPane.showMessageDialog(null, "Acesso Permitido!");
                TelaPrincipal tela = new TelaPrincipal();
                //Deixa uma janela visível(true), ou invisível(false)        
                tela.setVisible(true);
                //Fecha a janela para poder exibir a próxima
                dispose();
            }
        }
    }//GEN-LAST:event_cTxtSenhaTelaLoginKeyPressed

    private void cTxtUsuarioTelaLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtUsuarioTelaLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (cTxtUsuarioTelaLogin.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Está faltando o usuario!");
            } else if (cTxtSenhaTelaLogin.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Está faltando a senha!");
            } else if (!cTxtUsuarioTelaLogin.getText().equals("root")) {
                JOptionPane.showMessageDialog(null, "O usuario está incorreto!");
            } else if (!cTxtSenhaTelaLogin.getText().equals("1234")) {
                JOptionPane.showMessageDialog(null, "A senha está incorreta!");
            } else if (cTxtUsuarioTelaLogin.getText().equals("root") && cTxtSenhaTelaLogin.getText().equals("1234")) {
                JOptionPane.showMessageDialog(null, "Acesso Permitido!");
                TelaPrincipal tela = new TelaPrincipal();
                //Deixa uma janela visível(true), ou invisível(false)        
                tela.setVisible(true);
                //Fecha a janela para poder exibir a próxima
                dispose();
            }
        }
    }//GEN-LAST:event_cTxtUsuarioTelaLoginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new telaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntrarTelaLogin;
    private javax.swing.JPasswordField cTxtSenhaTelaLogin;
    private javax.swing.JTextField cTxtUsuarioTelaLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel painelTelaLogin;
    // End of variables declaration//GEN-END:variables
}
