/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.Banco;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import getSet.alunoGetSet;
import getSet.emprestimoGetSet;
import getSet.livroGetSet;
import getSet.professorGetSet;
import testeControle.controleEmprestimo;

/**
 *
 * @author Aluno
 */
public class TelaCadastroEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form TelaEmprestimo
     */
    public TelaCadastroEmprestimo() {
        initComponents();

        ImageIcon icone = new ImageIcon(getClass().getResource("/images/ceetecaicon16x16.png"));
        this.setIconImage(icone.getImage());

    }

    public TelaCadastroEmprestimo(TelaGerenciarEmprestimo telaAnterior) {
        this();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDadoUsuarioCadEmprestimo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cTxtNomeCadEmprestimo = new javax.swing.JTextField();
        btPesquisarCadEmprestimo = new javax.swing.JButton();
        cTxtCPFCadEmprestimo = new javax.swing.JFormattedTextField();
        cComboBoxTipoCadEmprestimo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        painelDadosExCadEmprestimo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cTxtNumChamadaCadEmprestimo = new javax.swing.JTextField();
        btBuscarCadEmprestimo = new javax.swing.JButton();
        lblNumChamadaCadEmprestimo = new javax.swing.JLabel();
        lblTituloCadEmprestimo = new javax.swing.JLabel();
        lblAutorCadEmprestimo = new javax.swing.JLabel();
        lblAssuntoCadEmprestimo = new javax.swing.JLabel();
        lblLiberadoCadEmprestimo = new javax.swing.JLabel();
        lblSituacaoCadEmprestimo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        painelDetalhamentoCadEmprestimo = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        cTxtDtDevolucaoCadEmprestimo = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cTxtAreaObservacoesCadEmprestimo = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btRegistrarCadEmprestimo = new javax.swing.JButton();
        btVoltarCadEmprestimo = new javax.swing.JButton();
        btLimparCadEmprestimo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CEETECA");
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Tipo:");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Nome:");

        jLabel5.setText("CPF:");

        cTxtNomeCadEmprestimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtNomeCadEmprestimoKeyReleased(evt);
            }
        });

        btPesquisarCadEmprestimo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btPesquisarCadEmprestimo.setText("Pesquisar");
        btPesquisarCadEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarCadEmprestimoActionPerformed(evt);
            }
        });

        try {
            cTxtCPFCadEmprestimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cComboBoxTipoCadEmprestimo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Aluno", "Professor" }));

        javax.swing.GroupLayout painelDadoUsuarioCadEmprestimoLayout = new javax.swing.GroupLayout(painelDadoUsuarioCadEmprestimo);
        painelDadoUsuarioCadEmprestimo.setLayout(painelDadoUsuarioCadEmprestimoLayout);
        painelDadoUsuarioCadEmprestimoLayout.setHorizontalGroup(
            painelDadoUsuarioCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadoUsuarioCadEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadoUsuarioCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDadoUsuarioCadEmprestimoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cTxtNomeCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDadoUsuarioCadEmprestimoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cComboBoxTipoCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cTxtCPFCadEmprestimo))
                    .addGroup(painelDadoUsuarioCadEmprestimoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btPesquisarCadEmprestimo)))
                .addGap(25, 25, 25))
        );
        painelDadoUsuarioCadEmprestimoLayout.setVerticalGroup(
            painelDadoUsuarioCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadoUsuarioCadEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadoUsuarioCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(cTxtCPFCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cComboBoxTipoCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(painelDadoUsuarioCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cTxtNomeCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btPesquisarCadEmprestimo)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setText("Dados Usuário");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setText("N° Chamada:");

        btBuscarCadEmprestimo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btBuscarCadEmprestimo.setText("Buscar");
        btBuscarCadEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarCadEmprestimoActionPerformed(evt);
            }
        });

        lblNumChamadaCadEmprestimo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblNumChamadaCadEmprestimo.setText("N° Chamada: ..........");

        lblTituloCadEmprestimo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblTituloCadEmprestimo.setText("Título: ..........");

        lblAutorCadEmprestimo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblAutorCadEmprestimo.setText("Autor: ..........");

        lblAssuntoCadEmprestimo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblAssuntoCadEmprestimo.setText("Assunto: ..........");

        lblLiberadoCadEmprestimo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblLiberadoCadEmprestimo.setText("Liberado para: ..........");

        lblSituacaoCadEmprestimo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblSituacaoCadEmprestimo.setText("Situação: ..........");

        javax.swing.GroupLayout painelDadosExCadEmprestimoLayout = new javax.swing.GroupLayout(painelDadosExCadEmprestimo);
        painelDadosExCadEmprestimo.setLayout(painelDadosExCadEmprestimoLayout);
        painelDadosExCadEmprestimoLayout.setHorizontalGroup(
            painelDadosExCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosExCadEmprestimoLayout.createSequentialGroup()
                .addGroup(painelDadosExCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosExCadEmprestimoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelDadosExCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosExCadEmprestimoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelDadosExCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btBuscarCadEmprestimo)
                                    .addComponent(cTxtNumChamadaCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblNumChamadaCadEmprestimo)))
                    .addGroup(painelDadosExCadEmprestimoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(painelDadosExCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAutorCadEmprestimo)
                            .addComponent(lblTituloCadEmprestimo)
                            .addComponent(lblAssuntoCadEmprestimo)
                            .addComponent(lblLiberadoCadEmprestimo)
                            .addComponent(lblSituacaoCadEmprestimo))))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        painelDadosExCadEmprestimoLayout.setVerticalGroup(
            painelDadosExCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosExCadEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosExCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cTxtNumChamadaCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btBuscarCadEmprestimo)
                .addGap(18, 18, 18)
                .addComponent(lblNumChamadaCadEmprestimo)
                .addGap(18, 18, 18)
                .addComponent(lblTituloCadEmprestimo)
                .addGap(18, 18, 18)
                .addComponent(lblAutorCadEmprestimo)
                .addGap(18, 18, 18)
                .addComponent(lblAssuntoCadEmprestimo)
                .addGap(18, 18, 18)
                .addComponent(lblLiberadoCadEmprestimo)
                .addGap(18, 18, 18)
                .addComponent(lblSituacaoCadEmprestimo)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setText("Dados Exemplar");

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel16.setText("Data para Devolução:");

        try {
            cTxtDtDevolucaoCadEmprestimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel17.setText("Observações:");

        cTxtAreaObservacoesCadEmprestimo.setColumns(20);
        cTxtAreaObservacoesCadEmprestimo.setRows(5);
        cTxtAreaObservacoesCadEmprestimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtAreaObservacoesCadEmprestimoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(cTxtAreaObservacoesCadEmprestimo);

        javax.swing.GroupLayout painelDetalhamentoCadEmprestimoLayout = new javax.swing.GroupLayout(painelDetalhamentoCadEmprestimo);
        painelDetalhamentoCadEmprestimo.setLayout(painelDetalhamentoCadEmprestimoLayout);
        painelDetalhamentoCadEmprestimoLayout.setHorizontalGroup(
            painelDetalhamentoCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDetalhamentoCadEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDetalhamentoCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDetalhamentoCadEmprestimoLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cTxtDtDevolucaoCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDetalhamentoCadEmprestimoLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        painelDetalhamentoCadEmprestimoLayout.setVerticalGroup(
            painelDetalhamentoCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDetalhamentoCadEmprestimoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(painelDetalhamentoCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cTxtDtDevolucaoCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDetalhamentoCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel15.setText("Detalhamento");

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel18.setText("CADASTRO DE EMPRÉSTIMO");

        btRegistrarCadEmprestimo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btRegistrarCadEmprestimo.setText("Registrar");
        btRegistrarCadEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarCadEmprestimoActionPerformed(evt);
            }
        });

        btVoltarCadEmprestimo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btVoltarCadEmprestimo.setText("Voltar");
        btVoltarCadEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarCadEmprestimoActionPerformed(evt);
            }
        });

        btLimparCadEmprestimo1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btLimparCadEmprestimo1.setText("Limpar");
        btLimparCadEmprestimo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparCadEmprestimo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(painelDadoUsuarioCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(painelDadosExCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(painelDetalhamentoCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRegistrarCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btLimparCadEmprestimo1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btVoltarCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDadoUsuarioCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDadosExCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDetalhamentoCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparCadEmprestimo1)
                    .addComponent(btVoltarCadEmprestimo)
                    .addComponent(btRegistrarCadEmprestimo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void limpar() {
        cTxtAreaObservacoesCadEmprestimo.setText("");
        cTxtCPFCadEmprestimo.setText("");
        cTxtDtDevolucaoCadEmprestimo.setText("");
        cTxtNomeCadEmprestimo.setText("");
        cTxtNumChamadaCadEmprestimo.setText("");
        cComboBoxTipoCadEmprestimo.setSelectedIndex(0);
    }
    private void btLimparCadEmprestimo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparCadEmprestimo1ActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparCadEmprestimo1ActionPerformed

    private void btVoltarCadEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarCadEmprestimoActionPerformed
        setVisible(false);
        new TelaGerenciarEmprestimo().setVisible(true);
    }//GEN-LAST:event_btVoltarCadEmprestimoActionPerformed

    private void btRegistrarCadEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarCadEmprestimoActionPerformed
        String areaObs = cTxtAreaObservacoesCadEmprestimo.getText();
        String cpf = cTxtCPFCadEmprestimo.getText();
        String dtDevolucao = cTxtDtDevolucaoCadEmprestimo.getText();
        String nome = cTxtNomeCadEmprestimo.getText();
        String numChamada = cTxtNumChamadaCadEmprestimo.getText();
        String tipo = String.valueOf(cComboBoxTipoCadEmprestimo.getSelectedIndex());
        emprestimoGetSet infos = new emprestimoGetSet();
        infos.setTipo(tipo);
        infos.setNome(nome);
        infos.setCpf(cpf);
        infos.setNumChamada(numChamada);
        infos.setObservacoes(areaObs);
        infos.setDtDevolucao(dtDevolucao);
        Banco.emprestimos.add(infos);
        controleEmprestimo controlador = new controleEmprestimo();
        if (controlador.TestaConferirEmprestimos(infos)) {
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Está faltando Dados");
        }
    }//GEN-LAST:event_btRegistrarCadEmprestimoActionPerformed


    private void btBuscarCadEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarCadEmprestimoActionPerformed
        //String nchamada = cTxtNumChamadaCadEmprestimo.getText();
        if (!cTxtNumChamadaCadEmprestimo.getText().equals("")) {
            for (int i = 0; i < Banco.livros.size(); i++) {
                livroGetSet livro = Banco.livros.get(i);
                emprestimoGetSet emprestimo = Banco.emprestimos.get(i);
                if (cTxtNumChamadaCadEmprestimo.getText().equals(livro.getNumChamada())) {
                    lblNumChamadaCadEmprestimo.setText("Nº Chamada :" + livro.getNumChamada());
                    lblTituloCadEmprestimo.setText("Titulo :" + livro.getTitulo());
                    lblAutorCadEmprestimo.setText("Autor :" + livro.getAutor());
                    lblAssuntoCadEmprestimo.setText("Assunto do Livro : " + livro.getAssunto());
                    lblLiberadoCadEmprestimo.setText("Liberado para :" + cTxtNomeCadEmprestimo.getText());
                    lblSituacaoCadEmprestimo.setText("Situação :" + emprestimo.getObservacoes());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não tem esse numero de chamada");
        }
    }//GEN-LAST:event_btBuscarCadEmprestimoActionPerformed

    private void btPesquisarCadEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarCadEmprestimoActionPerformed
//

        if (!cTxtNomeCadEmprestimo.getText().equals("")
                && !cTxtCPFCadEmprestimo.getText().equals("")
                && !cComboBoxTipoCadEmprestimo.equals(0)) {
            for (int i = 0; i < Banco.alunos.size(); i++) {
                alunoGetSet aluno = Banco.alunos.get(i);
                if (cTxtNomeCadEmprestimo.getText().equals(aluno.getNome())
                        && cTxtCPFCadEmprestimo.getText().equals(aluno.getCpf())
                        && cComboBoxTipoCadEmprestimo.equals(2)) {
                    JOptionPane.showMessageDialog(null, "Este aluno está cadastrada!");
                }
            }
        } else if (!cTxtNomeCadEmprestimo.getText().equals("")
                && !cTxtCPFCadEmprestimo.getText().equals("")
                && !cComboBoxTipoCadEmprestimo.equals(0)) {
            for (int i = 0; i < Banco.professores.size(); i++) {
                professorGetSet professor = Banco.professores.get(i);
                if (cTxtNomeCadEmprestimo.getText().equals(professor.getNome())
                        && cTxtCPFCadEmprestimo.getText().equals(professor.getCpf())
                        && cComboBoxTipoCadEmprestimo.equals(3)) {
                    JOptionPane.showMessageDialog(null, "Este professor está cadastrado");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não a ninguem com essas\n"
                    + "informações cadastrado");
        }


    }//GEN-LAST:event_btPesquisarCadEmprestimoActionPerformed

    private void cTxtNomeCadEmprestimoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtNomeCadEmprestimoKeyReleased
        // TODO add your handling code here:
        
        cTxtNomeCadEmprestimo.setText(cTxtNomeCadEmprestimo.getText().toUpperCase());
    }//GEN-LAST:event_cTxtNomeCadEmprestimoKeyReleased

    private void cTxtAreaObservacoesCadEmprestimoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtAreaObservacoesCadEmprestimoKeyReleased
        // TODO add your handling code here:
         cTxtAreaObservacoesCadEmprestimo.setText(cTxtAreaObservacoesCadEmprestimo.getText().toUpperCase());
    }//GEN-LAST:event_cTxtAreaObservacoesCadEmprestimoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarCadEmprestimo;
    private javax.swing.JButton btLimparCadEmprestimo1;
    private javax.swing.JButton btPesquisarCadEmprestimo;
    private javax.swing.JButton btRegistrarCadEmprestimo;
    private javax.swing.JButton btVoltarCadEmprestimo;
    private javax.swing.JComboBox<String> cComboBoxTipoCadEmprestimo;
    private javax.swing.JTextArea cTxtAreaObservacoesCadEmprestimo;
    private javax.swing.JFormattedTextField cTxtCPFCadEmprestimo;
    private javax.swing.JFormattedTextField cTxtDtDevolucaoCadEmprestimo;
    private javax.swing.JTextField cTxtNomeCadEmprestimo;
    private javax.swing.JTextField cTxtNumChamadaCadEmprestimo;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAssuntoCadEmprestimo;
    private javax.swing.JLabel lblAutorCadEmprestimo;
    private javax.swing.JLabel lblLiberadoCadEmprestimo;
    private javax.swing.JLabel lblNumChamadaCadEmprestimo;
    private javax.swing.JLabel lblSituacaoCadEmprestimo;
    private javax.swing.JLabel lblTituloCadEmprestimo;
    private javax.swing.JPanel painelDadoUsuarioCadEmprestimo;
    private javax.swing.JPanel painelDadosExCadEmprestimo;
    private javax.swing.JPanel painelDetalhamentoCadEmprestimo;
    // End of variables declaration//GEN-END:variables
}
