/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.Banco;
import java.text.DecimalFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import getSet.alunoGetSet;
import getSet.emprestimoGetSet;
import getSet.livroGetSet;
import getSet.professorGetSet;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author PC
 */
public class TelaPrincipal extends javax.swing.JFrame {

    DecimalFormat formatador = new DecimalFormat("00");

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();

        /* this.setExtendedState(this.MAXIMIZED_BOTH);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        //this.setMinimumSize(d);
        //int larg = d.width;
        int alt = d.height;

        alt = (int) (alt * 0.94);
        d.height = alt;
        //setSize(larg, (int)(alt*0.94));
        setSize(d);
        
         */
        Timer time = new Timer(500, ativar);
        time.start();

        ImageIcon icone = new ImageIcon(getClass().getResource("/images/ceetecaicon16x16.png"));
        this.setIconImage(icone.getImage());

    }

    public void ListarCadastros() {
        //Pegamos o modelo da tabela, as colunas.
        DefaultTableModel tableModel = (DefaultTableModel) tabelaTelaPrincipal.getModel();
        //Itera sobre os elementos no banco
        for (int i = 0; i < Banco.alunos.size(); i++) {
            //Pega o biliotecario
            alunoGetSet alunos = Banco.alunos.get(i);
            professorGetSet professor = Banco.professores.get(i);
            emprestimoGetSet emprestimo = Banco.emprestimos.get(i);
            livroGetSet livro = Banco.livros.get(i);

            if (alunos.getNome().equals(Banco.alunos)
                    && alunos.getCpf().equals(Banco.alunos)) {
                //Passa os dados do bibliotecario para um objeto
                Object[] linha = new Object[]{
                    alunos.getNome(),
                    alunos.getCpf(),
                    livro.getTitulo(),
                    emprestimo.getNumChamada(),
                    emprestimo.getDtDevolucao(),
                    emprestimo.getObservacoes()

                };
                //Adiciona o objeto na linha da coluna
                tableModel.addRow(linha);

            } else if (professor.getNome().equals(Banco.professores)
                    && professor.getCpf().equals(Banco.professores)) {
                Object[] linha = new Object[]{
                    professor.getNome(),
                    professor.getCpf(),
                    livro.getTitulo(),
                    emprestimo.getNumChamada(),
                    emprestimo.getDtDevolucao(),
                    emprestimo.getObservacoes()
                };

                tableModel.addRow(linha);
            }

        }
        //Definimos o modelo com as linhas adicionadas novamente para a tabela
        tabelaTelaPrincipal.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        painelTelaPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTelaPrincipal = new javax.swing.JTable();
        lbData = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        lbCumprimento = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        gerenciarTelaPrincipal = new javax.swing.JMenu();
        usuarioTelaPrincipal = new javax.swing.JMenu();
        gerAlunoPrincipal = new javax.swing.JMenuItem();
        gerBibliotecarioPrincipal = new javax.swing.JMenuItem();
        gerProfessorPrincipal = new javax.swing.JMenuItem();
        gerEmprestimoTelaPrincipal = new javax.swing.JMenuItem();
        gerLivroTelaPrincipal = new javax.swing.JMenuItem();
        ajudaTelaPrincipal = new javax.swing.JMenu();
        manualTelaPrincipal = new javax.swing.JMenuItem();
        sobreTelaPrincipal = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        jMenuItem13.setText("jMenuItem13");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CEETECA");
        setResizable(false);

        tabelaTelaPrincipal.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        tabelaTelaPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Matrícula / N° Funcional", "Título Livro", "Número Chamada", "Limite data", "Situação"
            }
        ));
        jScrollPane1.setViewportView(tabelaTelaPrincipal);

        javax.swing.GroupLayout painelTelaPrincipalLayout = new javax.swing.GroupLayout(painelTelaPrincipal);
        painelTelaPrincipal.setLayout(painelTelaPrincipalLayout);
        painelTelaPrincipalLayout.setHorizontalGroup(
            painelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelTelaPrincipalLayout.setVerticalGroup(
            painelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelaPrincipalLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        lbData.setText("                         Data");

        lbHora.setText("     Hora");

        gerenciarTelaPrincipal.setText("Gerenciar");

        usuarioTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario16x16.png"))); // NOI18N
        usuarioTelaPrincipal.setText("Pessoa");

        gerAlunoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AlunoPB16x16.png"))); // NOI18N
        gerAlunoPrincipal.setText("Aluno");
        gerAlunoPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerAlunoPrincipalActionPerformed(evt);
            }
        });
        usuarioTelaPrincipal.add(gerAlunoPrincipal);

        gerBibliotecarioPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GerenciarBibliotecarioPB16x16.png"))); // NOI18N
        gerBibliotecarioPrincipal.setText("Bibliotecário");
        gerBibliotecarioPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerBibliotecarioPrincipalActionPerformed(evt);
            }
        });
        usuarioTelaPrincipal.add(gerBibliotecarioPrincipal);

        gerProfessorPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gerenciarProfessorPB16x16.png"))); // NOI18N
        gerProfessorPrincipal.setText("Professor");
        gerProfessorPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerProfessorPrincipalActionPerformed(evt);
            }
        });
        usuarioTelaPrincipal.add(gerProfessorPrincipal);

        gerenciarTelaPrincipal.add(usuarioTelaPrincipal);

        gerEmprestimoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GerenciarEmprestimoPB16x16.png"))); // NOI18N
        gerEmprestimoTelaPrincipal.setText("Empréstimo");
        gerEmprestimoTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerEmprestimoTelaPrincipalActionPerformed(evt);
            }
        });
        gerenciarTelaPrincipal.add(gerEmprestimoTelaPrincipal);

        gerLivroTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LivroPB16x16.png"))); // NOI18N
        gerLivroTelaPrincipal.setText("Livro");
        gerLivroTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerLivroTelaPrincipalActionPerformed(evt);
            }
        });
        gerenciarTelaPrincipal.add(gerLivroTelaPrincipal);

        jMenuBar1.add(gerenciarTelaPrincipal);

        ajudaTelaPrincipal.setText("Ajuda");

        manualTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ManualPB16x16.png"))); // NOI18N
        manualTelaPrincipal.setText("Manual do Usuário");
        ajudaTelaPrincipal.add(manualTelaPrincipal);

        sobreTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sobrePB16.x16.png"))); // NOI18N
        sobreTelaPrincipal.setText("Sobre");
        ajudaTelaPrincipal.add(sobreTelaPrincipal);

        jMenuBar1.add(ajudaTelaPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbCumprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(lbData, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lbHora, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(painelTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbData)
                    .addComponent(lbHora)
                    .addComponent(lbCumprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerLivroTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerLivroTelaPrincipalActionPerformed
        // TODO add your handling code here:

        this.setVisible(true);
        new TelaGerenciarLivro().setVisible(true);

    }//GEN-LAST:event_gerLivroTelaPrincipalActionPerformed

    private void gerProfessorPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerProfessorPrincipalActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        new TelaGerenciarProfessor().setVisible(true);

    }//GEN-LAST:event_gerProfessorPrincipalActionPerformed

    private void gerAlunoPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerAlunoPrincipalActionPerformed
        // TODO add your handling code here:

        this.setVisible(true);
        new TelaGerenciarAluno().setVisible(true);
    }//GEN-LAST:event_gerAlunoPrincipalActionPerformed

    private void gerBibliotecarioPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerBibliotecarioPrincipalActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        new TelaGerenciarBibliotecario().setVisible(true);
    }//GEN-LAST:event_gerBibliotecarioPrincipalActionPerformed

    private void gerEmprestimoTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerEmprestimoTelaPrincipalActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        new TelaGerenciarEmprestimo().setVisible(true);
    }//GEN-LAST:event_gerEmprestimoTelaPrincipalActionPerformed

    ActionListener ativar = (new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            preencherHoras();
        }
    });

    public void preencherHoras() {
        Calendar horarioAtual = Calendar.getInstance();
        lbHora.setText(formatador.format(horarioAtual.get(Calendar.HOUR_OF_DAY)) + ":" + formatador.format(horarioAtual.get(Calendar.MINUTE)) + ":" + formatador.format(horarioAtual.get(Calendar.SECOND)));

        if (horarioAtual.get(Calendar.HOUR_OF_DAY) < 12) {
            lbCumprimento.setText("Bom dia!");
        } else if (horarioAtual.get(Calendar.HOUR_OF_DAY) < 18) {
            lbCumprimento.setText("Boa Tarde!");
        } else {
            lbCumprimento.setText("Boa Noite!");
        }

        String diaSemana = "", mes = "";

        switch (horarioAtual.get(Calendar.DAY_OF_WEEK)) {

            case 1:
                diaSemana = "Domingo, ";
                break;
            case 2:
                diaSemana = "Segunda-Feira, ";
                break;
            case 3:
                diaSemana = "Terça-Feira, ";
                break;
            case 4:
                diaSemana = "Quarta-Feira, ";
                break;
            case 5:
                diaSemana = "Quinta-Feira, ";
                break;
            case 6:
                diaSemana = "Sexta-Feira, ";
                break;
            case 7:
                diaSemana = "Sábado, ";
                break;

        }

        switch (horarioAtual.get(Calendar.MONTH) + 1) {

            case 1:
                mes = " de Janeiro de ";
                break;
            case 2:
                mes = " de Fevereiro de ";
                break;
            case 3:
                mes = " de Março de ";
                break;
            case 4:
                mes = " de Abril de ";
                break;
            case 5:
                mes = " de Maio de ";
                break;
            case 6:
                mes = " de Junho de ";
                break;
            case 7:
                mes = " de Julho de ";
                break;
            case 8:
                mes = " de Agosto de ";
                break;
            case 9:
                mes = " de Setembro de ";
                break;
            case 10:
                mes = " de Outubro de ";
                break;
            case 11:
                mes = " de Novembro de ";
                break;
            case 12:
                mes = " de Dezembro de ";
                break;

        }

        lbData.setText(diaSemana + horarioAtual.get(Calendar.DAY_OF_MONTH) + mes + horarioAtual.get(Calendar.YEAR));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajudaTelaPrincipal;
    private javax.swing.JMenuItem gerAlunoPrincipal;
    private javax.swing.JMenuItem gerBibliotecarioPrincipal;
    private javax.swing.JMenuItem gerEmprestimoTelaPrincipal;
    private javax.swing.JMenuItem gerLivroTelaPrincipal;
    private javax.swing.JMenuItem gerProfessorPrincipal;
    private javax.swing.JMenu gerenciarTelaPrincipal;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCumprimento;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbHora;
    private javax.swing.JMenuItem manualTelaPrincipal;
    private javax.swing.JPanel painelTelaPrincipal;
    private javax.swing.JMenuItem sobreTelaPrincipal;
    private javax.swing.JTable tabelaTelaPrincipal;
    private javax.swing.JMenu usuarioTelaPrincipal;
    // End of variables declaration//GEN-END:variables
}
