/*
 * Praticando criação de interface para o projeto CEETECA...
 *
 * São apenas ideias para o layout, e claro  serão alteradas ao
 * decorrer do projeto.
 */
package Telas;

import DAO.NewHibernateUtil;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import getSet.alunoGetSet;
import java.util.Date;
import java.util.List;
import javax.persistence.Query;
import models.Aluno;
import models.Curso;
import models.Modulo;
import models.Pessoa;
import models.Turno;
import org.hibernate.Session;
import testeControle.controleAluno;

/**
 *
 * @author Felipe Severo
 */
public class TelaCadastroAluno extends javax.swing.JFrame {
    
    
    /**
     * Creates new form TelaUsuario
     */
    public TelaCadastroAluno() {
        initComponents();
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/ceetecaicon16x16.png"));
        this.setIconImage(icone.getImage());

        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel3 = new javax.swing.JLabel();
        painelDadosCadEmprestimo = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        lbCPF = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        lbCelular = new javax.swing.JLabel();
        cTxtNomeCadAluno = new javax.swing.JTextField();
        cTxtCPFCadAluno = new javax.swing.JFormattedTextField();
        cTxtEmailCadAluno = new javax.swing.JTextField();
        cTxtTelefoneCadAluno = new javax.swing.JFormattedTextField();
        cTxtCelularCadAluno = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        cTxtDtNascimentoCadAluno = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        cTxtMatriculaCadAluno = new javax.swing.JFormattedTextField();
        painelComplementarCadEmprestimo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbCurso = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        lbBairro = new javax.swing.JLabel();
        lbCidade = new javax.swing.JLabel();
        cComboBoxCursoCadAluno = new javax.swing.JComboBox<>();
        cTxtRuaCadAluno = new javax.swing.JTextField();
        cTxtBairroCadAluno = new javax.swing.JTextField();
        cTxtCidadeCadAluno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cComboBoxTurnoCadAluno = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cComboBoxModuloCadAluno = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cTxtNumeroCadAluno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cComboBoxEstadoCadAluno = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cTxtComplementoCadAluno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cTxtCEPCadAluno = new javax.swing.JFormattedTextField();
        btLimparCadAluno = new javax.swing.JButton();
        btConfirmarCadAluno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btVoltarCadAluno = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CEETECA");
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Dados Pessoais");

        lbNome.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbNome.setText("Nome:");

        lbCPF.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbCPF.setText("CPF:");

        lbEmail.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbEmail.setText("E-mail:");

        lbTelefone.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbTelefone.setText("Telefone:");

        lbCelular.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbCelular.setText("Celular:");

        cTxtNomeCadAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtNomeCadAlunoKeyReleased(evt);
            }
        });

        try {
            cTxtCPFCadAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cTxtEmailCadAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtEmailCadAlunoKeyReleased(evt);
            }
        });

        try {
            cTxtTelefoneCadAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            cTxtCelularCadAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Matricula:");

        try {
            cTxtDtNascimentoCadAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Data de Nascimento:");

        try {
            cTxtMatriculaCadAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout painelDadosCadEmprestimoLayout = new javax.swing.GroupLayout(painelDadosCadEmprestimo);
        painelDadosCadEmprestimo.setLayout(painelDadosCadEmprestimoLayout);
        painelDadosCadEmprestimoLayout.setHorizontalGroup(
            painelDadosCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosCadEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosCadEmprestimoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cTxtEmailCadAluno))
                    .addGroup(painelDadosCadEmprestimoLayout.createSequentialGroup()
                        .addGroup(painelDadosCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosCadEmprestimoLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lbNome))
                            .addComponent(lbCPF, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cTxtCPFCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cTxtNomeCadAluno)))
                    .addGroup(painelDadosCadEmprestimoLayout.createSequentialGroup()
                        .addGroup(painelDadosCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosCadEmprestimoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbCelular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cTxtCelularCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDadosCadEmprestimoLayout.createSequentialGroup()
                                .addComponent(lbTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cTxtTelefoneCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelDadosCadEmprestimoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cTxtMatriculaCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224)))
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cTxtDtNascimentoCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelDadosCadEmprestimoLayout.setVerticalGroup(
            painelDadosCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosCadEmprestimoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(painelDadosCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cTxtMatriculaCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(cTxtNomeCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cTxtDtNascimentoCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(painelDadosCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCPF)
                    .addComponent(cTxtCPFCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(cTxtEmailCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefone)
                    .addComponent(cTxtTelefoneCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCelular)
                    .addComponent(cTxtCelularCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Complementar");

        lbCurso.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbCurso.setText("Curso:");

        lbEndereco.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbEndereco.setText("Av/Rua:");

        lbBairro.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbBairro.setText("Bairro:");

        lbCidade.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbCidade.setText("Cidade:");

        cComboBoxCursoCadAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Informática", "Jogos Digitais", "Redes" }));
        cComboBoxCursoCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cComboBoxCursoCadAlunoActionPerformed(evt);
            }
        });

        cTxtRuaCadAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtRuaCadAlunoKeyReleased(evt);
            }
        });

        cTxtBairroCadAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtBairroCadAlunoKeyReleased(evt);
            }
        });

        cTxtCidadeCadAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtCidadeCadAlunoKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Turno:");

        cComboBoxTurnoCadAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "M", "V", "N" }));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Módulo:");

        cComboBoxModuloCadAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "I", "II", "III", "IV" }));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("N°:");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Estado:");

        cComboBoxEstadoCadAluno.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cComboBoxEstadoCadAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Acre (AC)", "Alagoas (AL)", "Amapá (AP)", "Amazonas (AM)", "Bahia (BA)", "Ceará (CE)", "Distrito Federal (DF)", "Espírito Santo (ES)", "Goiás (GO)", "Maranhão (MA)", "Mato Grosso (MT)", "Mato Grosso do Sul (MS)", "Minas Gerais (MG)", "Pará (PA)", "Paraíba (PB)", "Paraná (PR)", "Pernambuco (PE)", "Piauí (PI)", "Rio de Janeiro (RJ)", "Rio Grande do Norte (RN)", "Rio Grande do Sul (RS)", "Rondônia (RO)", "Roraima (RR)", "Santa Catarina (SC)", "São Paulo (SP)", "Sergipe (SE)", "Tocantins (TO)" }));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Complemento:");

        cTxtComplementoCadAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtComplementoCadAlunoKeyReleased(evt);
            }
        });

        jLabel11.setText("CEP:");

        javax.swing.GroupLayout painelComplementarCadEmprestimoLayout = new javax.swing.GroupLayout(painelComplementarCadEmprestimo);
        painelComplementarCadEmprestimo.setLayout(painelComplementarCadEmprestimoLayout);
        painelComplementarCadEmprestimoLayout.setHorizontalGroup(
            painelComplementarCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelComplementarCadEmprestimoLayout.createSequentialGroup()
                .addGroup(painelComplementarCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEndereco)
                    .addComponent(lbCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbBairro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCidade, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelComplementarCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelComplementarCadEmprestimoLayout.createSequentialGroup()
                        .addGroup(painelComplementarCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painelComplementarCadEmprestimoLayout.createSequentialGroup()
                                .addComponent(cTxtRuaCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(9, 9, 9))
                            .addGroup(painelComplementarCadEmprestimoLayout.createSequentialGroup()
                                .addComponent(cComboBoxCursoCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(painelComplementarCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelComplementarCadEmprestimoLayout.createSequentialGroup()
                                .addComponent(cComboBoxTurnoCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cComboBoxModuloCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cTxtNumeroCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelComplementarCadEmprestimoLayout.createSequentialGroup()
                        .addGroup(painelComplementarCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cTxtBairroCadAluno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cTxtCidadeCadAluno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelComplementarCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(painelComplementarCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelComplementarCadEmprestimoLayout.createSequentialGroup()
                                .addComponent(cComboBoxEstadoCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cTxtComplementoCadAluno)))))
            .addGroup(painelComplementarCadEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelComplementarCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelComplementarCadEmprestimoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cTxtCEPCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelComplementarCadEmprestimoLayout.setVerticalGroup(
            painelComplementarCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelComplementarCadEmprestimoLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(painelComplementarCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cTxtCEPCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelComplementarCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCurso)
                    .addComponent(cComboBoxCursoCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cComboBoxTurnoCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cComboBoxModuloCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelComplementarCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(cTxtRuaCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cTxtNumeroCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelComplementarCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBairro)
                    .addComponent(cTxtBairroCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cTxtComplementoCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelComplementarCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCidade)
                    .addComponent(cTxtCidadeCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cComboBoxEstadoCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btLimparCadAluno.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btLimparCadAluno.setText("Limpar");
        btLimparCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparCadAlunoActionPerformed(evt);
            }
        });

        btConfirmarCadAluno.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btConfirmarCadAluno.setText("Confirmar");
        btConfirmarCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarCadAlunoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("CADASTRO DE ALUNO");

        btVoltarCadAluno.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btVoltarCadAluno.setText("Voltar");
        btVoltarCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarCadAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelComplementarCadEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(painelDadosCadEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btConfirmarCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btLimparCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btVoltarCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDadosCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelComplementarCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btVoltarCadAluno)
                            .addComponent(btLimparCadAluno)
                            .addComponent(btConfirmarCadAluno))
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cComboBoxCursoCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cComboBoxCursoCadAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cComboBoxCursoCadAlunoActionPerformed

    private void btLimparCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparCadAlunoActionPerformed
        // Aqui e para limpar a tela de alunos.

        Limpar();
    }//GEN-LAST:event_btLimparCadAlunoActionPerformed
    
    private void btConfirmarCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarCadAlunoActionPerformed
        // 
        
        String nome = cTxtNomeCadAluno.getText();
        String matricula = cTxtMatriculaCadAluno.getText();
        String cpf = cTxtCPFCadAluno.getText();
        String dtNascimento = cTxtDtNascimentoCadAluno.getText();
        String email = cTxtEmailCadAluno.getText();
        String celular = cTxtCelularCadAluno.getText();
        String telefone = cTxtTelefoneCadAluno.getText();
        String curso = String.valueOf(cComboBoxCursoCadAluno.getSelectedIndex());
        String modulo = String.valueOf(cComboBoxModuloCadAluno.getSelectedIndex());
        String turno = String.valueOf(cComboBoxTurnoCadAluno.getSelectedIndex());
        String estado = String.valueOf(cComboBoxEstadoCadAluno.getSelectedIndex());
        String rua = cTxtRuaCadAluno.getText();
        String numero = cTxtNumeroCadAluno.getText();
        String bairro = cTxtBairroCadAluno.getText();
        String cidade = cTxtCidadeCadAluno.getText();
        String cep = cTxtCEPCadAluno.getText();
        String complemento = cTxtComplementoCadAluno.getText();
        
        alunoGetSet infos = new alunoGetSet();
        
        infos.setNome(nome);
        infos.setNumMatricula(matricula);
        infos.setCpf(cpf);
        infos.setDtNascimento(dtNascimento);
        infos.setEmail(email);
        infos.setCelular(celular);
        infos.setTelefone(telefone);
        infos.setCurso(curso);
        infos.setModulo(modulo);
        infos.setTurno(turno);
        infos.setEstado(estado);
        infos.setLogradouro(rua);
        infos.setNumResidencia(numero);
        infos.setBairro(bairro);
        infos.setCidade(cidade);
        infos.setComplemento(complemento);
        infos.setCep(cep);
        
        controleAluno controlador = new controleAluno();
        if (controlador.TestaConferirAluno(infos)) {
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Está faltando dados, termine de preencher os campos");
        }
        
    }//GEN-LAST:event_btConfirmarCadAlunoActionPerformed

    private void btVoltarCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarCadAlunoActionPerformed
        // 
        setVisible(false);
        new TelaGerenciarAluno().setVisible(true);
    }//GEN-LAST:event_btVoltarCadAlunoActionPerformed

    private void cTxtNomeCadAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtNomeCadAlunoKeyReleased
        // TODO add your handling code here:
        
         cTxtNomeCadAluno.setText(cTxtNomeCadAluno.getText().toUpperCase());
    }//GEN-LAST:event_cTxtNomeCadAlunoKeyReleased

    private void cTxtEmailCadAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtEmailCadAlunoKeyReleased
        // TODO add your handling code here:
        cTxtEmailCadAluno.setText(cTxtEmailCadAluno.getText().toUpperCase());
    }//GEN-LAST:event_cTxtEmailCadAlunoKeyReleased

    private void cTxtRuaCadAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtRuaCadAlunoKeyReleased
        // TODO add your handling code here:
        
        cTxtRuaCadAluno.setText(cTxtRuaCadAluno.getText().toUpperCase());
    }//GEN-LAST:event_cTxtRuaCadAlunoKeyReleased

    private void cTxtBairroCadAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtBairroCadAlunoKeyReleased
        // TODO add your handling code here:
        
        cTxtBairroCadAluno.setText(cTxtBairroCadAluno.getText().toUpperCase());
    }//GEN-LAST:event_cTxtBairroCadAlunoKeyReleased

    private void cTxtComplementoCadAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtComplementoCadAlunoKeyReleased
        // TODO add your handling code here:
        
        cTxtComplementoCadAluno.setText(cTxtComplementoCadAluno.getText().toUpperCase());
    }//GEN-LAST:event_cTxtComplementoCadAlunoKeyReleased

    private void cTxtCidadeCadAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtCidadeCadAlunoKeyReleased
        // TODO add your handling code here:
        
        cTxtCidadeCadAluno.setText(cTxtCidadeCadAluno.getText().toUpperCase());
    }//GEN-LAST:event_cTxtCidadeCadAlunoKeyReleased

    public void Limpar() {
        //Dados Pessoais
        cTxtMatriculaCadAluno.setText("");
        cTxtNomeCadAluno.setText("");
        cTxtCPFCadAluno.setText("");
        cTxtDtNascimentoCadAluno.setText("");

        //Contato
        cTxtEmailCadAluno.setText("");
        cTxtTelefoneCadAluno.setText("");
        cTxtCelularCadAluno.setText("");

        //endereço
        cComboBoxCursoCadAluno.setSelectedIndex(0);
        cComboBoxModuloCadAluno.setSelectedIndex(0);
        cComboBoxTurnoCadAluno.setSelectedIndex(0);
        cComboBoxEstadoCadAluno.setSelectedIndex(0);
        cTxtRuaCadAluno.setText("");
        cTxtNumeroCadAluno.setText("");
        cTxtBairroCadAluno.setText("");
        cTxtCidadeCadAluno.setText("");
        cTxtComplementoCadAluno.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmarCadAluno;
    private javax.swing.JButton btLimparCadAluno;
    private javax.swing.JButton btVoltarCadAluno;
    private javax.swing.JComboBox<String> cComboBoxCursoCadAluno;
    private javax.swing.JComboBox<String> cComboBoxEstadoCadAluno;
    private javax.swing.JComboBox<String> cComboBoxModuloCadAluno;
    private javax.swing.JComboBox<String> cComboBoxTurnoCadAluno;
    private javax.swing.JTextField cTxtBairroCadAluno;
    private javax.swing.JFormattedTextField cTxtCEPCadAluno;
    private javax.swing.JFormattedTextField cTxtCPFCadAluno;
    private javax.swing.JFormattedTextField cTxtCelularCadAluno;
    private javax.swing.JTextField cTxtCidadeCadAluno;
    private javax.swing.JTextField cTxtComplementoCadAluno;
    private javax.swing.JFormattedTextField cTxtDtNascimentoCadAluno;
    private javax.swing.JTextField cTxtEmailCadAluno;
    private javax.swing.JFormattedTextField cTxtMatriculaCadAluno;
    private javax.swing.JTextField cTxtNomeCadAluno;
    private javax.swing.JTextField cTxtNumeroCadAluno;
    private javax.swing.JTextField cTxtRuaCadAluno;
    private javax.swing.JFormattedTextField cTxtTelefoneCadAluno;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbCelular;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbCurso;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JPanel painelComplementarCadEmprestimo;
    private javax.swing.JPanel painelDadosCadEmprestimo;
    // End of variables declaration//GEN-END:variables
}
