/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.NewHibernateUtil;
import javax.swing.ImageIcon;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Query;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import models.Contato;
import models.Curso;
import models.Endereco;
import models.Pessoa;
import models.Professor;
import models.ProfessorHasCurso;
import org.hibernate.Session;

/**
 *
 * @author Aluno
 */
public class TelaCadProfessor extends javax.swing.JFrame {

    /**
     *
     * Creates new form TelaCadProfessor
     */
    
    /*ADMINISTRAÇÃO, COMÉRCIO EXTERIOR, EVENTOS, GASTRONOMIA, INFORMÁTICA, MODELAGEM DO VESTUÁRIO, MULTIMÍDIA, PRODUÇÃO DE MODA, PROGRAMAÇÃO DE JOGOS DIGITAIS, RADIO E TV, REDES DE COMPUTADORES*/
    public TelaCadProfessor() {
        initComponents();

        ImageIcon icone = new ImageIcon(getClass().getResource("/images/ceetecaicon16x16.png"));
        this.setIconImage(icone.getImage());
        
        try(Session sessaoAtual = NewHibernateUtil.getSessionFactory().openSession()){
            sessaoAtual.beginTransaction();
            Query q = sessaoAtual.createQuery("FROM Curso");
            List<Curso> cursos = q.getResultList();
            DefaultListModel listModel = new DefaultListModel<Curso>();
            for (Curso c : cursos) {
                listModel.addElement(c);
            }
            cxListModelo.setModel(listModel);
            cxListModelo.setVisible(true);
            sessaoAtual.getTransaction().commit();
            sessaoAtual.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro:"+e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeralCadProfessor = new javax.swing.JPanel();
        painelDadosCadProfessor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cTxtNomeCadProfessor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cTxtNumFuncionalCadProfessor = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        cTxtDtNascimentoCadProfessor = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        cTxtCPFCadProfessor = new javax.swing.JFormattedTextField();
        butAdicionarCurso = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        cxListModelo = new javax.swing.JList<>();
        butRemoverCurso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cxListSelecionados = new javax.swing.JList<>();
        painelEnderecoCadProfessor = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cTxtCEPCadProfessor = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        cTxtRuaCadProfessor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cTxtNumeroCadProfessor = new javax.swing.JTextField();
        cTxtBairroCadProfessor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cTxtCidadeCadProfessor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cComboBoxUFCadProfessor = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cTxtComplementoCadProfessor = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        PainelContatoCadProfessor = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cTxtCelularCadProfessor = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        cTxtTelefoneCadProfessor = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        cTxtEmailCadProfessor = new javax.swing.JTextField();
        btConfirmarCadProfessor = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btLimparCadProfessor = new javax.swing.JButton();
        btVoltarCadProfessor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CEETECA");
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        cTxtNomeCadProfessor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtNomeCadProfessorKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Nº Funcional:");

        try {
            cTxtNumFuncionalCadProfessor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Data de Nascimento:");

        try {
            cTxtDtNascimentoCadProfessor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setText("CPF:");

        try {
            cTxtCPFCadProfessor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        butAdicionarCurso.setText(">>>");
        butAdicionarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAdicionarCursoActionPerformed(evt);
            }
        });
        butAdicionarCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                butAdicionarCursoKeyReleased(evt);
            }
        });

        cxListModelo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(cxListModelo);

        butRemoverCurso.setText("<<<");
        butRemoverCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRemoverCursoActionPerformed(evt);
            }
        });
        butRemoverCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                butRemoverCursoKeyReleased(evt);
            }
        });

        cxListSelecionados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(cxListSelecionados);

        javax.swing.GroupLayout painelDadosCadProfessorLayout = new javax.swing.GroupLayout(painelDadosCadProfessor);
        painelDadosCadProfessor.setLayout(painelDadosCadProfessorLayout);
        painelDadosCadProfessorLayout.setHorizontalGroup(
            painelDadosCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosCadProfessorLayout.createSequentialGroup()
                .addGroup(painelDadosCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosCadProfessorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelDadosCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosCadProfessorLayout.createSequentialGroup()
                                .addGroup(painelDadosCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelDadosCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cTxtCPFCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cTxtNumFuncionalCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cTxtDtNascimentoCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDadosCadProfessorLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(painelDadosCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(butAdicionarCurso)
                                    .addComponent(butRemoverCurso))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painelDadosCadProfessorLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cTxtNomeCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        painelDadosCadProfessorLayout.setVerticalGroup(
            painelDadosCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosCadProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cTxtNomeCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cTxtNumFuncionalCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cTxtDtNascimentoCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cTxtCPFCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(painelDadosCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosCadProfessorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butAdicionarCurso)
                        .addGap(18, 18, 18)
                        .addComponent(butRemoverCurso)
                        .addGap(24, 24, 24))
                    .addGroup(painelDadosCadProfessorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(painelDadosCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))))
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("CEP:");

        try {
            cTxtCEPCadProfessor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel11.setText("Av/Rua:");

        cTxtRuaCadProfessor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtRuaCadProfessorKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setText("Nº:");

        cTxtBairroCadProfessor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtBairroCadProfessorKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setText("Bairro:");

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setText("Cidade:");

        cTxtCidadeCadProfessor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtCidadeCadProfessorKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setText("Estado/UF:");

        cComboBoxUFCadProfessor.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cComboBoxUFCadProfessor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Acre (AC)", "Alagoas (AL)", "Amapá (AP)", "Amazonas (AM)", "Bahia (BA)", "Ceará (CE)", "Distrito Federal (DF)", "Espírito Santo (ES)", "Goiás (GO)", "Maranhão (MA)", "Mato Grosso (MT)", "Mato Grosso do Sul (MS)", "Minas Gerais (MG)", "Pará (PA)", "Paraíba (PB)", "Paraná (PR)", "Pernambuco (PE) Piauí (PI)", "Rio de Janeiro (RJ)", "Rio Grande do Norte (RN)", "Rio Grande do Sul (RS)", "Rondônia (RO)", "Roraima (RR)", "Santa Catarina (SC)", "São Paulo (SP)", "Sergipe (SE)", "Tocantins (TO)" }));
        cComboBoxUFCadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cComboBoxUFCadProfessorActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel16.setText("Endereço");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Complemento:");

        cTxtComplementoCadProfessor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtComplementoCadProfessorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout painelEnderecoCadProfessorLayout = new javax.swing.GroupLayout(painelEnderecoCadProfessor);
        painelEnderecoCadProfessor.setLayout(painelEnderecoCadProfessorLayout);
        painelEnderecoCadProfessorLayout.setHorizontalGroup(
            painelEnderecoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecoCadProfessorLayout.createSequentialGroup()
                .addGroup(painelEnderecoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEnderecoCadProfessorLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cTxtCEPCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelEnderecoCadProfessorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(painelEnderecoCadProfessorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelEnderecoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(painelEnderecoCadProfessorLayout.createSequentialGroup()
                                .addGroup(painelEnderecoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelEnderecoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(painelEnderecoCadProfessorLayout.createSequentialGroup()
                                        .addComponent(cTxtRuaCadProfessor)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cTxtNumeroCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))
                                    .addGroup(painelEnderecoCadProfessorLayout.createSequentialGroup()
                                        .addGroup(painelEnderecoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cTxtCidadeCadProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                            .addComponent(cTxtBairroCadProfessor))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(painelEnderecoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(painelEnderecoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(painelEnderecoCadProfessorLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(cComboBoxUFCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cTxtComplementoCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelEnderecoCadProfessorLayout.setVerticalGroup(
            painelEnderecoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEnderecoCadProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(painelEnderecoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cTxtCEPCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(7, 7, 7)
                .addGroup(painelEnderecoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cTxtRuaCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cTxtNumeroCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(painelEnderecoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cTxtBairroCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9)
                    .addComponent(cTxtComplementoCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelEnderecoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cTxtCidadeCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cComboBoxUFCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel17.setText("Contato");

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel18.setText("Celular:");

        try {
            cTxtCelularCadProfessor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel19.setText("Telefone:");

        try {
            cTxtTelefoneCadProfessor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel20.setText("E-mail:");

        cTxtEmailCadProfessor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtEmailCadProfessorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout PainelContatoCadProfessorLayout = new javax.swing.GroupLayout(PainelContatoCadProfessor);
        PainelContatoCadProfessor.setLayout(PainelContatoCadProfessorLayout);
        PainelContatoCadProfessorLayout.setHorizontalGroup(
            PainelContatoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelContatoCadProfessorLayout.createSequentialGroup()
                .addGroup(PainelContatoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelContatoCadProfessorLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(PainelContatoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelContatoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PainelContatoCadProfessorLayout.createSequentialGroup()
                                .addComponent(cTxtCelularCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cTxtTelefoneCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cTxtEmailCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelContatoCadProfessorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelContatoCadProfessorLayout.setVerticalGroup(
            PainelContatoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelContatoCadProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(PainelContatoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cTxtCelularCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(cTxtTelefoneCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelContatoCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cTxtEmailCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btConfirmarCadProfessor.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btConfirmarCadProfessor.setText("Confirmar");
        btConfirmarCadProfessor.setPreferredSize(new java.awt.Dimension(110, 25));
        btConfirmarCadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarCadProfessorActionPerformed(evt);
            }
        });

        btLimparCadProfessor.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btLimparCadProfessor.setText("Limpar");
        btLimparCadProfessor.setPreferredSize(new java.awt.Dimension(110, 25));
        btLimparCadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparCadProfessorActionPerformed(evt);
            }
        });

        btVoltarCadProfessor.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btVoltarCadProfessor.setText("Voltar");
        btVoltarCadProfessor.setPreferredSize(new java.awt.Dimension(110, 25));
        btVoltarCadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarCadProfessorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Dados");

        javax.swing.GroupLayout painelGeralCadProfessorLayout = new javax.swing.GroupLayout(painelGeralCadProfessor);
        painelGeralCadProfessor.setLayout(painelGeralCadProfessorLayout);
        painelGeralCadProfessorLayout.setHorizontalGroup(
            painelGeralCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGeralCadProfessorLayout.createSequentialGroup()
                .addComponent(painelDadosCadProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2))
            .addComponent(painelEnderecoCadProfessor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 629, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGeralCadProfessorLayout.createSequentialGroup()
                .addGroup(painelGeralCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGeralCadProfessorLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btConfirmarCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btLimparCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btVoltarCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PainelContatoCadProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(painelGeralCadProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 577, Short.MAX_VALUE))
        );
        painelGeralCadProfessorLayout.setVerticalGroup(
            painelGeralCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGeralCadProfessorLayout.createSequentialGroup()
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(painelGeralCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelDadosCadProfessor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelEnderecoCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelContatoCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelGeralCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLimparCadProfessor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelGeralCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btVoltarCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btConfirmarCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CADASTRO DE PROFESSOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelGeralCadProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelGeralCadProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cComboBoxUFCadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cComboBoxUFCadProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cComboBoxUFCadProfessorActionPerformed

    private void btLimparCadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparCadProfessorActionPerformed
        // TODO add your handling code here:

        Limpar();

    }//GEN-LAST:event_btLimparCadProfessorActionPerformed

    private void btConfirmarCadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarCadProfessorActionPerformed
        // TODO add your handling code here:
       
        String nome = cTxtNomeCadProfessor.getText();
        String numFuncional = cTxtNumFuncionalCadProfessor.getText();
        String cpf = cTxtCPFCadProfessor.getText();
        
        Date dtNascimento = null;
        try {
            SimpleDateFormat in = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");
            dtNascimento = out.parse(cTxtDtNascimentoCadProfessor.getText());
        } catch (ParseException ex) {
            Logger.getLogger(TelaCadBibliotecario.class.getName()).log(Level.SEVERE, null, ex);
        }

        int numero = Integer.parseInt(cTxtNumeroCadProfessor.getText());
        
        String cep = cTxtCEPCadProfessor.getText();
        String email = cTxtEmailCadProfessor.getText();
        String celular = cTxtCelularCadProfessor.getText();
        String telefone = cTxtTelefoneCadProfessor.getText();
        String cursoSelecionado = String.valueOf(cxListSelecionados.getSelectedIndex());
        String estado = String.valueOf(cComboBoxUFCadProfessor.getSelectedIndex());
        String logradouro = cTxtRuaCadProfessor.getText();
        String bairro = cTxtBairroCadProfessor.getText();
        String cidade = cTxtCidadeCadProfessor.getText();
        String complemento = cTxtComplementoCadProfessor.getText();

        Pessoa pss = new Pessoa();
        pss.setNomePessoa(nome);
        pss.setMatriculaPessoa(numFuncional);
        pss.setCpfPessoa(cpf);
        pss.setDtnascimento(dtNascimento);

        Contato ctt = new Contato();
        ctt.setEmailContato(email);
        ctt.setCelularContato(celular);
        ctt.setTelefoneContato(telefone);
        ctt.setPessoa(pss);

        Endereco end = new Endereco();
        end.setBairroEndereco(bairro);
        end.setCep(cep);
        end.setCidadeEndereco(cidade);
        end.setComplementoEndereco(complemento);
        end.setEstadoEndereco(estado);
        end.setLogradouroEndereco(logradouro);
        end.setNumeroEndereco(numero);
        end.setPessoa(pss);

        ArrayList<Curso> cursosSelecionados = new ArrayList<Curso>();
        
        DefaultListModel<Curso> cursinhos = (DefaultListModel<Curso>) cxListSelecionados.getModel();
        
        for (int i = 0; i < cursinhos.size(); i++) {
            cursosSelecionados.add(cursinhos.get(i));
        }
        
        Professor prf = new Professor();
        prf.setPessoa(pss);

        int resposta = JOptionPane.showConfirmDialog(null, "Deseja confirmar o cadastro?", "", JOptionPane.YES_NO_OPTION);
        
        if (resposta == JOptionPane.YES_OPTION) {
            try (Session actualSession = NewHibernateUtil.getSessionFactory().openSession()) {
                actualSession.beginTransaction();
                
                actualSession.saveOrUpdate(pss);
                actualSession.saveOrUpdate(ctt);
                actualSession.saveOrUpdate(end);
                actualSession.saveOrUpdate(prf);
                ProfessorHasCurso phc = null;
                for (int i = 0; i < cursosSelecionados.size(); i++) {
                    phc = new ProfessorHasCurso();
                    phc.setCurso(cursosSelecionados.get(i));
                    phc.setProfessor(prf);
                    actualSession.saveOrUpdate(phc);
                }
                actualSession.getTransaction().commit();
                actualSession.close();
                
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Usuário não cadastrado. Devido ao erro " + e.getMessage());
                NewHibernateUtil.getSessionFactory().getCurrentSession().close();
            }
        } else if (resposta == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Cadastro não efetuado");
        }
    }//GEN-LAST:event_btConfirmarCadProfessorActionPerformed

     public void SetInformacoes(Professor prof){
        cTxtNomeCadProfessor.setText(prof.getPessoa().getNomePessoa());
        cTxtCPFCadProfessor.setText(prof.getPessoa().getCpfPessoa());
        cTxtNumFuncionalCadProfessor.setText(prof.getPessoa().getMatriculaPessoa());
        SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");
        cTxtDtNascimentoCadProfessor.setText(out.format(prof.getPessoa().getDtnascimento()));
        ArrayList <Contato> contatos = new ArrayList(prof.getPessoa().getContatos());
        cTxtEmailCadProfessor.setText(contatos.get(0).getEmailContato());
        cTxtCelularCadProfessor.setText(contatos.get(0).getCelularContato());
        cTxtTelefoneCadProfessor.setText(contatos.get(0).getTelefoneContato());
        ArrayList <Endereco> enderecos = new ArrayList(prof.getPessoa().getEnderecos());
        cTxtCEPCadProfessor.setText(enderecos.get(0).getCep());
        cTxtBairroCadProfessor.setText(enderecos.get(0).getBairroEndereco());
        cTxtCidadeCadProfessor.setText(enderecos.get(0).getCidadeEndereco());
        cTxtComplementoCadProfessor.setText(enderecos.get(0).getComplementoEndereco());
        cComboBoxUFCadProfessor.setSelectedItem(enderecos.get(0).getEstadoEndereco());
        cTxtRuaCadProfessor.setText(enderecos.get(0).getLogradouroEndereco());
        cTxtNumeroCadProfessor.setText(String.valueOf(enderecos.get(0).getNumeroEndereco()));
    }
    
     
     
    private void btVoltarCadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarCadProfessorActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        new TelaGerenciarProfessor().setVisible(true);

    }//GEN-LAST:event_btVoltarCadProfessorActionPerformed

    private void cTxtNomeCadProfessorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtNomeCadProfessorKeyReleased
        // TODO add your handling code here:
        cTxtNomeCadProfessor.setText(cTxtNomeCadProfessor.getText().toUpperCase());
    }//GEN-LAST:event_cTxtNomeCadProfessorKeyReleased

    private void cTxtRuaCadProfessorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtRuaCadProfessorKeyReleased
        // TODO add your handling code here:
        cTxtRuaCadProfessor.setText(cTxtRuaCadProfessor.getText().toUpperCase());
    }//GEN-LAST:event_cTxtRuaCadProfessorKeyReleased

    private void cTxtBairroCadProfessorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtBairroCadProfessorKeyReleased
        // TODO add your handling code here:
        cTxtBairroCadProfessor.setText(cTxtBairroCadProfessor.getText().toUpperCase());
    }//GEN-LAST:event_cTxtBairroCadProfessorKeyReleased

    private void cTxtComplementoCadProfessorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtComplementoCadProfessorKeyReleased
        // TODO add your handling code here:
        cTxtComplementoCadProfessor.setText(cTxtComplementoCadProfessor.getText().toUpperCase());
    }//GEN-LAST:event_cTxtComplementoCadProfessorKeyReleased

    private void cTxtCidadeCadProfessorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtCidadeCadProfessorKeyReleased
        // TODO add your handling code here:
        cTxtCidadeCadProfessor.setText(cTxtCidadeCadProfessor.getText().toUpperCase());
    }//GEN-LAST:event_cTxtCidadeCadProfessorKeyReleased

    private void cTxtEmailCadProfessorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtEmailCadProfessorKeyReleased
        // TODO add your handling code here:
        cTxtEmailCadProfessor.setText(cTxtEmailCadProfessor.getText().toLowerCase());
    }//GEN-LAST:event_cTxtEmailCadProfessorKeyReleased

    private void butAdicionarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAdicionarCursoActionPerformed
        Curso curso = cxListModelo.getSelectedValue();

        ListModel lm = cxListSelecionados.getModel();
        DefaultListModel cursosPegos = new DefaultListModel();
        for (int i = 0; i < lm.getSize(); i++) {
            cursosPegos.addElement(lm.getElementAt(i));
        }
        cursosPegos.addElement(curso);
        cxListSelecionados.setModel(cursosPegos);
        cxListSelecionados.setVisible(true);

        ListModel modeloDisponiveis = cxListModelo.getModel();
        DefaultListModel cursosDisponiveis = new DefaultListModel();
        for (int i = 0; i < modeloDisponiveis.getSize(); i++) {
            cursosDisponiveis.addElement(modeloDisponiveis.getElementAt(i));
        }
        cursosDisponiveis.removeElement(curso);
        cxListModelo.setModel(cursosDisponiveis);
        cxListModelo.setVisible(true);
    }//GEN-LAST:event_butAdicionarCursoActionPerformed

    private void butAdicionarCursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_butAdicionarCursoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_butAdicionarCursoKeyReleased

    private void butRemoverCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRemoverCursoActionPerformed
        Curso curso = cxListSelecionados.getSelectedValue();
        if (curso != null) {
            ListModel lm = cxListModelo.getModel();
            DefaultListModel cursosPegos = new DefaultListModel();
            for (int i = 0; i < lm.getSize(); i++) {
                cursosPegos.addElement(lm.getElementAt(i));
            }
            cursosPegos.addElement(curso);
            cxListModelo.setModel(cursosPegos);
            cxListModelo.setVisible(true);

            ListModel modeloDisponiveis = cxListSelecionados.getModel();
            DefaultListModel cursosDisponiveis = new DefaultListModel();
            for (int i = 0; i < modeloDisponiveis.getSize(); i++) {
                cursosDisponiveis.addElement(modeloDisponiveis.getElementAt(i));
            }
            cursosDisponiveis.removeElement(curso);
            cxListSelecionados.setModel(cursosDisponiveis);
            cxListSelecionados.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Nulo!");
        }

    }//GEN-LAST:event_butRemoverCursoActionPerformed

    private void butRemoverCursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_butRemoverCursoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_butRemoverCursoKeyReleased

    public void Limpar() {

        //Dados Pessoais
        cTxtNumFuncionalCadProfessor.setText("");
        cTxtNomeCadProfessor.setText("");
        cTxtCPFCadProfessor.setText("");
        cTxtDtNascimentoCadProfessor.setText("");

        //Contato
        cTxtEmailCadProfessor.setText("");
        cTxtTelefoneCadProfessor.setText("");
        cTxtCelularCadProfessor.setText("");

        //endereço
        cComboBoxUFCadProfessor.setSelectedIndex(0);
        cTxtRuaCadProfessor.setText("");
        cTxtNumeroCadProfessor.setText("");
        cTxtBairroCadProfessor.setText("");
        cTxtCidadeCadProfessor.setText("");
        cTxtComplementoCadProfessor.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelContatoCadProfessor;
    private javax.swing.JButton btConfirmarCadProfessor;
    private javax.swing.JButton btLimparCadProfessor;
    private javax.swing.JButton btVoltarCadProfessor;
    private javax.swing.JButton butAdicionarCurso;
    private javax.swing.JButton butRemoverCurso;
    private javax.swing.JComboBox<String> cComboBoxUFCadProfessor;
    private javax.swing.JTextField cTxtBairroCadProfessor;
    private javax.swing.JFormattedTextField cTxtCEPCadProfessor;
    private javax.swing.JFormattedTextField cTxtCPFCadProfessor;
    private javax.swing.JFormattedTextField cTxtCelularCadProfessor;
    private javax.swing.JTextField cTxtCidadeCadProfessor;
    private javax.swing.JTextField cTxtComplementoCadProfessor;
    private javax.swing.JFormattedTextField cTxtDtNascimentoCadProfessor;
    private javax.swing.JTextField cTxtEmailCadProfessor;
    private javax.swing.JTextField cTxtNomeCadProfessor;
    private javax.swing.JFormattedTextField cTxtNumFuncionalCadProfessor;
    private javax.swing.JTextField cTxtNumeroCadProfessor;
    private javax.swing.JTextField cTxtRuaCadProfessor;
    private javax.swing.JFormattedTextField cTxtTelefoneCadProfessor;
    private javax.swing.JList<Curso> cxListModelo;
    private javax.swing.JList<Curso> cxListSelecionados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel painelDadosCadProfessor;
    private javax.swing.JPanel painelEnderecoCadProfessor;
    private javax.swing.JPanel painelGeralCadProfessor;
    // End of variables declaration//GEN-END:variables
}
