/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.NewHibernateUtil;
import com.mysql.cj.core.util.StringUtils;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Aluno;
import models.Emprestimo;
import models.Livro;
import models.Pessoa;
import models.Professor;
import org.hibernate.Session;

/**
 *
 * @author Aluno
 */
public class TelaCadastroEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form TelaEmprestimo
     */
    public TelaCadastroEmprestimo() {
        initComponents();

        ImageIcon icone = new ImageIcon(getClass().getResource("/images/ceetecaicon16x16.png"));
        this.setIconImage(icone.getImage());

    }

    public TelaCadastroEmprestimo(TelaGerenciarEmprestimo telaAnterior) {
        this();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDadoUsuarioCadEmprestimo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cTxtNomeCadEmprestimo = new javax.swing.JTextField();
        btPesquisarCadEmprestimo = new javax.swing.JButton();
        cTxtCPFCadEmprestimo = new javax.swing.JFormattedTextField();
        cComboBoxTipoCadEmprestimo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        painelDadosExCadEmprestimo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cTxtNumChamadaCadEmprestimo = new javax.swing.JTextField();
        btBuscarCadEmprestimo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAdvertencia = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        painelDetalhamentoCadEmprestimo = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        cTxtDtDevolucaoCadEmprestimo = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        cComboBoxSituacaoObs = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btRegistrarCadEmprestimo = new javax.swing.JButton();
        btVoltarCadEmprestimo = new javax.swing.JButton();
        btLimparCadEmprestimo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CEETECA");
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Tipo:");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Nome:");

        jLabel5.setText("CPF:");

        cTxtNomeCadEmprestimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtNomeCadEmprestimoKeyReleased(evt);
            }
        });

        btPesquisarCadEmprestimo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btPesquisarCadEmprestimo.setText("Pesquisar");
        btPesquisarCadEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarCadEmprestimoActionPerformed(evt);
            }
        });

        try {
            cTxtCPFCadEmprestimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cComboBoxTipoCadEmprestimo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Aluno", "Professor" }));

        javax.swing.GroupLayout painelDadoUsuarioCadEmprestimoLayout = new javax.swing.GroupLayout(painelDadoUsuarioCadEmprestimo);
        painelDadoUsuarioCadEmprestimo.setLayout(painelDadoUsuarioCadEmprestimoLayout);
        painelDadoUsuarioCadEmprestimoLayout.setHorizontalGroup(
            painelDadoUsuarioCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadoUsuarioCadEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadoUsuarioCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDadoUsuarioCadEmprestimoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cTxtNomeCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDadoUsuarioCadEmprestimoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cComboBoxTipoCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cTxtCPFCadEmprestimo))
                    .addGroup(painelDadoUsuarioCadEmprestimoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btPesquisarCadEmprestimo)))
                .addGap(25, 25, 25))
        );
        painelDadoUsuarioCadEmprestimoLayout.setVerticalGroup(
            painelDadoUsuarioCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadoUsuarioCadEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadoUsuarioCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(cTxtCPFCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cComboBoxTipoCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(painelDadoUsuarioCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cTxtNomeCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btPesquisarCadEmprestimo)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setText("Dados Usuário");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setText("N° Chamada:");

        btBuscarCadEmprestimo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btBuscarCadEmprestimo.setText("Buscar");
        btBuscarCadEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarCadEmprestimoActionPerformed(evt);
            }
        });

        tabelaAdvertencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº Chamada", "Autor", "Assunto", "Titulo", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaAdvertencia);

        javax.swing.GroupLayout painelDadosExCadEmprestimoLayout = new javax.swing.GroupLayout(painelDadosExCadEmprestimo);
        painelDadosExCadEmprestimo.setLayout(painelDadosExCadEmprestimoLayout);
        painelDadosExCadEmprestimoLayout.setHorizontalGroup(
            painelDadosExCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosExCadEmprestimoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosExCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btBuscarCadEmprestimo)
                    .addComponent(cTxtNumChamadaCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelDadosExCadEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        painelDadosExCadEmprestimoLayout.setVerticalGroup(
            painelDadosExCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosExCadEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosExCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cTxtNumChamadaCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btBuscarCadEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setText("Dados Exemplar");

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel16.setText("Data para Devolução:");

        try {
            cTxtDtDevolucaoCadEmprestimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel17.setText("Observações:");

        cComboBoxSituacaoObs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Em aberto", "Finalizado", " " }));

        javax.swing.GroupLayout painelDetalhamentoCadEmprestimoLayout = new javax.swing.GroupLayout(painelDetalhamentoCadEmprestimo);
        painelDetalhamentoCadEmprestimo.setLayout(painelDetalhamentoCadEmprestimoLayout);
        painelDetalhamentoCadEmprestimoLayout.setHorizontalGroup(
            painelDetalhamentoCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDetalhamentoCadEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDetalhamentoCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDetalhamentoCadEmprestimoLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cTxtDtDevolucaoCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDetalhamentoCadEmprestimoLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cComboBoxSituacaoObs, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        painelDetalhamentoCadEmprestimoLayout.setVerticalGroup(
            painelDetalhamentoCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDetalhamentoCadEmprestimoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(painelDetalhamentoCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cTxtDtDevolucaoCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDetalhamentoCadEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cComboBoxSituacaoObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel15.setText("Detalhamento");

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel18.setText("CADASTRO DE EMPRÉSTIMO");

        btRegistrarCadEmprestimo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btRegistrarCadEmprestimo.setText("Registrar");
        btRegistrarCadEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarCadEmprestimoActionPerformed(evt);
            }
        });

        btVoltarCadEmprestimo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btVoltarCadEmprestimo.setText("Voltar");
        btVoltarCadEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarCadEmprestimoActionPerformed(evt);
            }
        });

        btLimparCadEmprestimo1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btLimparCadEmprestimo1.setText("Limpar");
        btLimparCadEmprestimo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparCadEmprestimo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRegistrarCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btLimparCadEmprestimo1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btVoltarCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelDadosExCadEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel15)
                                    .addComponent(painelDetalhamentoCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(painelDadoUsuarioCadEmprestimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDadoUsuarioCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDadosExCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDetalhamentoCadEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparCadEmprestimo1)
                    .addComponent(btVoltarCadEmprestimo)
                    .addComponent(btRegistrarCadEmprestimo))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void limpar() {
        cComboBoxSituacaoObs.setSelectedIndex(0);
        cTxtCPFCadEmprestimo.setText("");
        cTxtDtDevolucaoCadEmprestimo.setText("");
        cTxtNomeCadEmprestimo.setText("");
        cTxtNumChamadaCadEmprestimo.setText("");
        cComboBoxTipoCadEmprestimo.setSelectedIndex(0);
    }
    private void btLimparCadEmprestimo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparCadEmprestimo1ActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparCadEmprestimo1ActionPerformed

    private void btVoltarCadEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarCadEmprestimoActionPerformed
        setVisible(false);
        new TelaGerenciarEmprestimo().setVisible(true);
    }//GEN-LAST:event_btVoltarCadEmprestimoActionPerformed

    private void btRegistrarCadEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarCadEmprestimoActionPerformed

        int resposta1 = JOptionPane.showConfirmDialog(null, "Deseja registrar empréstimo?", "", JOptionPane.YES_NO_OPTION);
        if (resposta1 == JOptionPane.YES_OPTION) {

            String areaObs = String.valueOf(cComboBoxSituacaoObs.getSelectedIndex());
            String cpf = cTxtCPFCadEmprestimo.getText();
            Date dtDevolucao = null;
            try {
                SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");
                SimpleDateFormat in = new SimpleDateFormat("yyyy-MM-dd");
                dtDevolucao = in.parse(cTxtDtDevolucaoCadEmprestimo.getText());
            } catch (ParseException ex) {
                Logger.getLogger(TelaCadBibliotecario.class.getName()).log(Level.SEVERE, null, ex);
            }
            String nome = cTxtNomeCadEmprestimo.getText();
            int numChamadaLivro = Integer.parseInt(cTxtNumChamadaCadEmprestimo.getText());
            String tipo = String.valueOf(cComboBoxTipoCadEmprestimo.getSelectedIndex());

            switch (tipo) {
                case "1": {
                    Pessoa pss = new Pessoa();
                    pss.setNomePessoa(nome);
                    pss.setCpfPessoa(cpf);
                    Livro lvr = new Livro();
                    lvr.setCddLivro(numChamadaLivro);//REAVALIAR.
                    Emprestimo emp = new Emprestimo();
                    emp.setDtDevolucaoEmprestimo(dtDevolucao);
                    emp.setObservacaoEmprestimo(areaObs);
                    Aluno aln = new Aluno();
                    aln.setPessoa(pss);

                    int resposta = JOptionPane.showConfirmDialog(null, "Deseja confirmar o usuário cadastrado?");
                    switch (resposta) {
                        case JOptionPane.YES_OPTION:
                            try (Session actualSession = NewHibernateUtil.getSessionFactory().openSession()) {
                                actualSession.beginTransaction();
                                actualSession.saveOrUpdate(pss);
                                actualSession.saveOrUpdate(lvr);
                                actualSession.saveOrUpdate(emp);
                                actualSession.saveOrUpdate(aln);
                                actualSession.getTransaction().commit();
                                actualSession.close();
                                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, "Usuário não cadastrado. Devido ao erro " + e.getMessage());
                                NewHibernateUtil.getSessionFactory().getCurrentSession().close();
                            }
                            break;
                        case JOptionPane.NO_OPTION:
                            JOptionPane.showMessageDialog(null, "Usuário não cadastrado.");
                            break;

                    }
                    break;
                }
                case "2": {
                    Pessoa pss = new Pessoa();
                    pss.setNomePessoa(nome);
                    pss.setCpfPessoa(cpf);
                    Livro lvr = new Livro();
                    lvr.setCddLivro(numChamadaLivro);//REAVALIAR.
                    Emprestimo emp = new Emprestimo();
                    emp.setDtDevolucaoEmprestimo(dtDevolucao);
                    emp.setObservacaoEmprestimo(areaObs);
                    Professor prf = new Professor();
                    prf.setPessoa(pss);

                    int resposta = JOptionPane.showConfirmDialog(null, "Deseja confirmar o usuário cadastrado?");
                    switch (resposta) {
                        case JOptionPane.YES_OPTION:
                            try (Session actualSession = NewHibernateUtil.getSessionFactory().openSession()) {
                                actualSession.beginTransaction();
                                actualSession.saveOrUpdate(pss);
                                actualSession.saveOrUpdate(lvr);
                                actualSession.saveOrUpdate(emp);
                                actualSession.saveOrUpdate(prf);
                                actualSession.getTransaction().commit();
                                actualSession.close();
                                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, "Usuário não cadastrado. Devido ao erro " + e.getMessage());
                                NewHibernateUtil.getSessionFactory().getCurrentSession().close();
                            }
                        case JOptionPane.NO_OPTION:
                            JOptionPane.showMessageDialog(null, "Usuário não cadastrado.");
                            break;
                    }
                }
                break;

                default:
                    JOptionPane.showMessageDialog(null, "Selecione uma opção:"
                            + "1 - Aluno"
                            + "2 - Professor");
                    break;
            }
        }

    }//GEN-LAST:event_btRegistrarCadEmprestimoActionPerformed


    private void btBuscarCadEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarCadEmprestimoActionPerformed
        
        
    }//GEN-LAST:event_btBuscarCadEmprestimoActionPerformed

    private void btPesquisarCadEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarCadEmprestimoActionPerformed
        
    }//GEN-LAST:event_btPesquisarCadEmprestimoActionPerformed

    private void cTxtNomeCadEmprestimoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtNomeCadEmprestimoKeyReleased
        // TODO add your handling code here:

        cTxtNomeCadEmprestimo.setText(cTxtNomeCadEmprestimo.getText().toUpperCase());
    }//GEN-LAST:event_cTxtNomeCadEmprestimoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarCadEmprestimo;
    private javax.swing.JButton btLimparCadEmprestimo1;
    private javax.swing.JButton btPesquisarCadEmprestimo;
    private javax.swing.JButton btRegistrarCadEmprestimo;
    private javax.swing.JButton btVoltarCadEmprestimo;
    private javax.swing.JComboBox<String> cComboBoxSituacaoObs;
    private javax.swing.JComboBox<String> cComboBoxTipoCadEmprestimo;
    private javax.swing.JFormattedTextField cTxtCPFCadEmprestimo;
    private javax.swing.JFormattedTextField cTxtDtDevolucaoCadEmprestimo;
    private javax.swing.JTextField cTxtNomeCadEmprestimo;
    private javax.swing.JTextField cTxtNumChamadaCadEmprestimo;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel painelDadoUsuarioCadEmprestimo;
    private javax.swing.JPanel painelDadosExCadEmprestimo;
    private javax.swing.JPanel painelDetalhamentoCadEmprestimo;
    private javax.swing.JTable tabelaAdvertencia;
    // End of variables declaration//GEN-END:variables
}
