/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.NewHibernateUtil;
import com.mysql.cj.core.util.StringUtils;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.persistence.Query;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import models.Advertencia;
import models.Aluno;
import models.Emprestimo;
import models.Exemplar;
import models.Livro;
import models.LivroHasEmprestimo;
import org.hibernate.Session;

/**
 *
 * @author Aluno
 */
public class TelaGerenciarLivro extends javax.swing.JFrame {

    /**
     * Creates new form TelaLivroGerenciar
     */
    public TelaGerenciarLivro() {
        initComponents();

        ImageIcon icone = new ImageIcon(getClass().getResource("/images/ceetecaicon16x16.png"));
        this.setIconImage(icone.getImage());

        listarCadastros();

    }

    public void listarCadastros() {
        Session sessao = NewHibernateUtil.getSessionFactory().openSession();
        sessao.beginTransaction();
        //Chama a view  //p.idPessoa
        Query q = sessao.createSQLQuery("SELECT distinct l.idLivro as N_Chamada ,\n"
                + "l.tituloLivro as Titulo,\n"
                + "l.autorLivro as Autor,\n"
                + "l.assunto as Assunto,\n"
                + "l.editoraLivro as Editora,\n"
                + "e.quantidadeExemplar as Quantidade\n"
                + "\n"
                + "FROM livro l, exemplar e\n"
                + "\n"
                + "WHERE l.idlivro = e.livro_idLivro\n"
                + "order by l.idLivro;").addEntity(viewmodel.viewGerLivro.class);

        //pega o resultado da query e retorna uma lista
        List<viewmodel.viewGerLivro> registrosTelaLivro = q.getResultList();
        sessao.getTransaction().commit();
        sessao.close();

        //pega o modelo da tabela
        DefaultTableModel model = (DefaultTableModel) tabelaGerLivro.getModel();

        for (int i = 0; i < registrosTelaLivro.size(); i++) {
            //Pega o dado do registro usando i
            viewmodel.viewGerLivro registro = registrosTelaLivro.get(i);
            //adiciona os valores na linha
            Object[] row = {
                registro.getnChamada(),
                registro.getTitulo(),
                registro.getAutor(),
                registro.getAssunto(),
                registro.getEditora(),
                registro.getQuantidadeEx()
            };
            //adiciona a linha no modelo da tabela
            model.addRow(row);
        }
        //adiciona o modelo novamente na tabela
        tabelaGerLivro.setModel(model);

        //Atualiza a parte grafica da tabela mostrando os novos valores
        tabelaGerLivro.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        painelGerLivro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cTxtBuscaGerLivro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaGerLivro = new javax.swing.JTable();
        btVoltarGerLivro = new javax.swing.JButton();
        btExcluirGerLivro = new javax.swing.JButton();
        btEditarGerLivro = new javax.swing.JButton();
        btCadastrarGerLivro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CEETECA");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("GERENCIAMENTO DE LIVRO");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Busca");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Termo para a busca:");

        cTxtBuscaGerLivro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cTxtBuscaGerLivroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtBuscaGerLivroKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("(Digite o título ou  nome do autor!)");

        javax.swing.GroupLayout painelGerLivroLayout = new javax.swing.GroupLayout(painelGerLivro);
        painelGerLivro.setLayout(painelGerLivroLayout);
        painelGerLivroLayout.setHorizontalGroup(
            painelGerLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGerLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelGerLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cTxtBuscaGerLivro)
                    .addGroup(painelGerLivroLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(0, 424, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelGerLivroLayout.setVerticalGroup(
            painelGerLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGerLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelGerLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cTxtBuscaGerLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tabelaGerLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Chamada", "Título", "Autor", "Assunto", "Editora", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaGerLivro);

        btVoltarGerLivro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btVoltarGerLivro.setText("Voltar");
        btVoltarGerLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarGerLivroActionPerformed(evt);
            }
        });

        btExcluirGerLivro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btExcluirGerLivro.setText("Excluir");
        btExcluirGerLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirGerLivroActionPerformed(evt);
            }
        });

        btEditarGerLivro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btEditarGerLivro.setText("Editar");

        btCadastrarGerLivro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btCadastrarGerLivro.setText("Cadastrar");
        btCadastrarGerLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarGerLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jSeparator2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                            .addComponent(painelGerLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCadastrarGerLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btEditarGerLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btExcluirGerLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btVoltarGerLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(painelGerLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCadastrarGerLivro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btExcluirGerLivro)
                        .addComponent(btVoltarGerLivro)
                        .addComponent(btEditarGerLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarGerLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarGerLivroActionPerformed
        // TODO add your handling code here:

        //TelaCadastroLivro telaLivro = new TelaCadastroLivro();
        this.setVisible(false);
        new TelaCadastroLivro().setVisible(true);

    }//GEN-LAST:event_btCadastrarGerLivroActionPerformed

    private void btVoltarGerLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarGerLivroActionPerformed
        // 
        setVisible(false);
        new TelaPrincipal().setVisible(true);

    }//GEN-LAST:event_btVoltarGerLivroActionPerformed

    private void btExcluirGerLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirGerLivroActionPerformed

        int sim = JOptionPane.showConfirmDialog(null, "Deseja excluir?", "", JOptionPane.YES_NO_OPTION);

        if (sim == JOptionPane.YES_NO_OPTION) {

            DefaultTableModel dtm = (DefaultTableModel) tabelaGerLivro.getModel();

            //Pega a linha da jtable
            Vector row = (Vector) dtm.getDataVector().elementAt(tabelaGerLivro.getSelectedRow());

            //Abre a sessão
            Session sessaoAtual = NewHibernateUtil.getSessionFactory().openSession();
            //Inicia uma transação com o banco
            sessaoAtual.beginTransaction();

            //Pega o primeiro valor da linha
            int id = (int) row.get(0);

            //Pega o objeto no banco pelo o id
            Livro livro = (Livro) sessaoAtual.get(Livro.class, id);
            
            List<Exemplar> exemplares = new ArrayList<>(livro.getExemplars());

            for (Exemplar exemplar : exemplares) {
                ArrayList<LivroHasEmprestimo> livroHasEmprestimos = new ArrayList<>(exemplar.getLivroHasEmprestimos());
                for(LivroHasEmprestimo emprestimoLivro : livroHasEmprestimos){
                    sessaoAtual.remove(emprestimoLivro);
                }
                sessaoAtual.remove(exemplar);
            }
            sessaoAtual.getTransaction().commit();
            sessaoAtual.beginTransaction();

            List<Emprestimo> emprestimos = new ArrayList<>(livro.getExemplars());

            for (Emprestimo emprestimo : emprestimos) {
                sessaoAtual.remove(emprestimo);
            }
            sessaoAtual.getTransaction().commit();
            sessaoAtual.beginTransaction();

            //Deleta o objeto do banco
            sessaoAtual.remove(livro);
            sessaoAtual.getTransaction().commit();
            sessaoAtual.close();
            JOptionPane.showMessageDialog(null, "Excluído com sucesso");

        } else {
            JOptionPane.showMessageDialog(null, "Exclusão não realizada");
        }

    }//GEN-LAST:event_btExcluirGerLivroActionPerformed

    private void cTxtBuscaGerLivroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtBuscaGerLivroKeyReleased

    }//GEN-LAST:event_cTxtBuscaGerLivroKeyReleased

    private void cTxtBuscaGerLivroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtBuscaGerLivroKeyPressed
        /*
        cTxtBuscaGerLivro.setText(cTxtBuscaGerLivro.getText().toUpperCase());
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER
                && StringUtils.isEmptyOrWhitespaceOnly(cTxtBuscaGerLivro.getText())) {
            Session sessao = NewHibernateUtil.getSessionFactory().openSession();
            sessao.beginTransaction();
            if (cTxtBuscaGerLivro == Livro) {
                
                Query q = sessao.createSQLQuery("select distinct l.idLivro as N_Chamada, \n"
                        + "l.tituloLivro as Titulo, \n"
                        + "l.autorLivro as Autor\n"
                        + "from livro l;");
                
            }
            sessao.getTransaction().commit();
            sessao.close();
            
        }
         */
    }//GEN-LAST:event_cTxtBuscaGerLivroKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciarLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarGerLivro;
    private javax.swing.JButton btEditarGerLivro;
    private javax.swing.JButton btExcluirGerLivro;
    private javax.swing.JButton btVoltarGerLivro;
    private javax.swing.JTextField cTxtBuscaGerLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel painelGerLivro;
    private javax.swing.JTable tabelaGerLivro;
    // End of variables declaration//GEN-END:variables
}
