/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;


import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import getSet.emprestimoGetSet;

/**
 *
 * @author PC
 */
public class TelaGerenciarEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form TelaEmprestimoGerenciar
     */
    public TelaGerenciarEmprestimo() {
        initComponents();
        
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/ceetecaicon16x16.png"));
        this.setIconImage(icone.getImage());
        
        ListarCadastros();
    }
    public void ListarCadastros(){
        //Pegamos o modelo da tabela, as colunas.
        DefaultTableModel tableModel = (DefaultTableModel) tabelaGerEmprestimo.getModel();
        //Itera sobre os elementos no banco
        for (int i = 0; i < Banco.emprestimos.size(); i++) {
            //Pega o biliotecario
            emprestimoGetSet emprestimo = Banco.emprestimos.get(i);
            
            //Passa os dados do bibliotecario para um objeto
            Object[] linha = new Object[]{
                emprestimo.getNome(),
                emprestimo.getCpf(),
                emprestimo.getTipo(),
                emprestimo.getNumChamada(),
                emprestimo.getObservacoes(),
                emprestimo.getDtDevolucao()
            };
            //Adiciona o objeto na linha da coluna
            tableModel.addRow(linha);
        }
        //Definimos o modelo com as linhas adicionadas novamente para a tabela
        tabelaGerEmprestimo.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGerEmprestimo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cTxtBuscaGerEmprestimo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaGerEmprestimo = new javax.swing.JTable();
        cCheckBoxGerEmprestimo = new javax.swing.JCheckBox();
        btCadastrarGerEmprestimos = new javax.swing.JButton();
        btCadastrarGerEmprestimos1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btVoltarGerEmprestimos = new javax.swing.JButton();
        btAdvertenciaGerEmprestimos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Termo para busca:");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("(Digite o nome do usuário ou do autor!)");

        cTxtBuscaGerEmprestimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtBuscaGerEmprestimoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout painelGerEmprestimoLayout = new javax.swing.GroupLayout(painelGerEmprestimo);
        painelGerEmprestimo.setLayout(painelGerEmprestimoLayout);
        painelGerEmprestimoLayout.setHorizontalGroup(
            painelGerEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGerEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelGerEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cTxtBuscaGerEmprestimo)
                    .addGroup(painelGerEmprestimoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelGerEmprestimoLayout.setVerticalGroup(
            painelGerEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGerEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelGerEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cTxtBuscaGerEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("GERENCIAMENTO DE EMPRÉSTIMOS");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Busca");

        tabelaGerEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Título", "N° Chamada", "Data Limite", "Situação"
            }
        ));
        jScrollPane1.setViewportView(tabelaGerEmprestimo);

        cCheckBoxGerEmprestimo.setText("Mostrar todos os empréstimos em aberto/finalizado.");
        cCheckBoxGerEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCheckBoxGerEmprestimoActionPerformed(evt);
            }
        });

        btCadastrarGerEmprestimos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btCadastrarGerEmprestimos.setText("Cadastrar");
        btCadastrarGerEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarGerEmprestimosActionPerformed(evt);
            }
        });

        btCadastrarGerEmprestimos1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btCadastrarGerEmprestimos1.setText("Finalizar");
        btCadastrarGerEmprestimos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarGerEmprestimos1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setText("*Para concluir o emprestimo clique em FINALIZAR");

        btVoltarGerEmprestimos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btVoltarGerEmprestimos.setText("Voltar");
        btVoltarGerEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarGerEmprestimosActionPerformed(evt);
            }
        });

        btAdvertenciaGerEmprestimos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btAdvertenciaGerEmprestimos.setText("Advertência");
        btAdvertenciaGerEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdvertenciaGerEmprestimosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cCheckBoxGerEmprestimo)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addComponent(painelGerEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addComponent(btAdvertenciaGerEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(btCadastrarGerEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(btCadastrarGerEmprestimos1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(btVoltarGerEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(painelGerEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrarGerEmprestimos)
                    .addComponent(btCadastrarGerEmprestimos1)
                    .addComponent(btVoltarGerEmprestimos)
                    .addComponent(btAdvertenciaGerEmprestimos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(cCheckBoxGerEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarGerEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarGerEmprestimosActionPerformed
        // TODO add your handling code here:
        
        
        setVisible(false);
        new TelaCadastroEmprestimo().setVisible(true);
        
    }//GEN-LAST:event_btCadastrarGerEmprestimosActionPerformed

    private void btCadastrarGerEmprestimos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarGerEmprestimos1ActionPerformed
        //             
    }//GEN-LAST:event_btCadastrarGerEmprestimos1ActionPerformed

    private void btVoltarGerEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarGerEmprestimosActionPerformed

        
        setVisible(false);
        new TelaPrincipal().setVisible(true);
    }//GEN-LAST:event_btVoltarGerEmprestimosActionPerformed

    private void cCheckBoxGerEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCheckBoxGerEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCheckBoxGerEmprestimoActionPerformed

    private void btAdvertenciaGerEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdvertenciaGerEmprestimosActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
        new TelaAdvertencia().setVisible(true);
    }//GEN-LAST:event_btAdvertenciaGerEmprestimosActionPerformed

    private void cTxtBuscaGerEmprestimoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtBuscaGerEmprestimoKeyReleased
        // TODO add your handling code here:
        
        cTxtBuscaGerEmprestimo.setText(cTxtBuscaGerEmprestimo.getText().toUpperCase());
    }//GEN-LAST:event_cTxtBuscaGerEmprestimoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciarEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdvertenciaGerEmprestimos;
    private javax.swing.JButton btCadastrarGerEmprestimos;
    private javax.swing.JButton btCadastrarGerEmprestimos1;
    private javax.swing.JButton btVoltarGerEmprestimos;
    private javax.swing.JCheckBox cCheckBoxGerEmprestimo;
    private javax.swing.JTextField cTxtBuscaGerEmprestimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel painelGerEmprestimo;
    private javax.swing.JTable tabelaGerEmprestimo;
    // End of variables declaration//GEN-END:variables
}
