/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;


import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class TelaGerenciarLivro extends javax.swing.JFrame {

    /**
     * Creates new form TelaLivroGerenciar
     */
    public TelaGerenciarLivro() {
        initComponents();
        
        ImageIcon icone = new ImageIcon(getClass().getResource("/images/ceetecaicon16x16.png"));
        this.setIconImage(icone.getImage());
            
        //ListarCadastros();
        
    }
    
        /*public void ListarCadastros(){
        //Pegamos o modelo da tabela, as colunas.
        DefaultTableModel tableModel = (DefaultTableModel) tabelaGerLivro.getModel();
        //Itera sobre os elementos no banco
        for (int i = 0; i < Banco.livros.size(); i++) {
            //Pega o biliotecario
            livroGetSet livro = Banco.livros.get(i);
            //Passa os dados do bibliotecario para um objeto
            Object[] linha = new Object[]{
                livro.getIsbn(),
                livro.getTitulo(),
                livro.getAutor(),
                livro.getAssunto(),
                livro.getEditora(),
                livro.getIdioma(),
                livro.getQtdExemplar()
            };
            //Adiciona o objeto na linha da coluna
            tableModel.addRow(linha);
        }
        //Definimos o modelo com as linhas adicionadas novamente para a tabela
        tabelaGerLivro.setModel(tableModel);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        painelGerLivro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cTxtBuscaGerLivro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaGerLivro = new javax.swing.JTable();
        btVoltarGerLivro = new javax.swing.JButton();
        btExcluirGerLivro = new javax.swing.JButton();
        btEditarGerLivro = new javax.swing.JButton();
        btCadastrarGerLivro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CEETECA");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("GERENCIAMENTO DE LIVRO");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Busca");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Termo para a busca:");

        cTxtBuscaGerLivro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cTxtBuscaGerLivroKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("(Digite o título ou  nome do autor!)");

        javax.swing.GroupLayout painelGerLivroLayout = new javax.swing.GroupLayout(painelGerLivro);
        painelGerLivro.setLayout(painelGerLivroLayout);
        painelGerLivroLayout.setHorizontalGroup(
            painelGerLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGerLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelGerLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cTxtBuscaGerLivro)
                    .addGroup(painelGerLivroLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(0, 424, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelGerLivroLayout.setVerticalGroup(
            painelGerLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGerLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelGerLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cTxtBuscaGerLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tabelaGerLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N° Chamada", "Título", "Autor", "Assunto", "Editora", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(tabelaGerLivro);

        btVoltarGerLivro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btVoltarGerLivro.setText("Voltar");
        btVoltarGerLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarGerLivroActionPerformed(evt);
            }
        });

        btExcluirGerLivro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btExcluirGerLivro.setText("Excluir");
        btExcluirGerLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirGerLivroActionPerformed(evt);
            }
        });

        btEditarGerLivro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btEditarGerLivro.setText("Editar");

        btCadastrarGerLivro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btCadastrarGerLivro.setText("Cadastrar");
        btCadastrarGerLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarGerLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jSeparator2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                            .addComponent(painelGerLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCadastrarGerLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btEditarGerLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btExcluirGerLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btVoltarGerLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(painelGerLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCadastrarGerLivro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btExcluirGerLivro)
                        .addComponent(btVoltarGerLivro)
                        .addComponent(btEditarGerLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarGerLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarGerLivroActionPerformed
        // TODO add your handling code here:
        
        //TelaCadastroLivro telaLivro = new TelaCadastroLivro();
        this.setVisible(false);
        new TelaCadastroLivro().setVisible(true);
        
    }//GEN-LAST:event_btCadastrarGerLivroActionPerformed

    private void btVoltarGerLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarGerLivroActionPerformed
        // 
        setVisible(false);
        new TelaPrincipal().setVisible(true);
        
    }//GEN-LAST:event_btVoltarGerLivroActionPerformed

    private void btExcluirGerLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirGerLivroActionPerformed
        // TODO add your handling code here:
       /* 
        if (tabelaGerLivro.getSelectedRow() != -1) {

            if (JOptionPane.showConfirmDialog(rootPane, "<html>Tem certeza que deseja remover<br>o seguinte usuário: <b>" + //(tabelaGerLivro.getSelectedRow()).getNome() + "?</b></html>", "Confirmar exclusão") == 0) {
                //usuarioBD.removerUsuario(modelo.retornarListaUsuarios().get(tabelaGerLivro.getSelectedRow()).getId());
                //preencherTabela();
                cTxtBuscaGerLivro.setText("");
                tabelaGerLivro.clearSelection();
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Por favor, selecione um Usuário!", "Impossível remover", 2);
        }
        */
    }//GEN-LAST:event_btExcluirGerLivroActionPerformed

    private void cTxtBuscaGerLivroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTxtBuscaGerLivroKeyReleased
        // TODO add your handling code here:
        
         cTxtBuscaGerLivro.setText(cTxtBuscaGerLivro.getText().toUpperCase());
    }//GEN-LAST:event_cTxtBuscaGerLivroKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciarLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarGerLivro;
    private javax.swing.JButton btEditarGerLivro;
    private javax.swing.JButton btExcluirGerLivro;
    private javax.swing.JButton btVoltarGerLivro;
    private javax.swing.JTextField cTxtBuscaGerLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel painelGerLivro;
    private javax.swing.JTable tabelaGerLivro;
    // End of variables declaration//GEN-END:variables
}
