package models;
// Generated 20/11/2018 13:58:57 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Advertencia generated by hbm2java
 */
public class Advertencia  implements java.io.Serializable {


     private int codigoAdvertencia;
     private LivroHasEmprestimo livroHasEmprestimo;
     private String descricaoAdvertencia;
     private Date dtAdvertencia;

    public Advertencia() {
    }

    public Advertencia(int codigoAdvertencia, LivroHasEmprestimo livroHasEmprestimo, String descricaoAdvertencia, Date dtAdvertencia) {
       this.codigoAdvertencia = codigoAdvertencia;
       this.livroHasEmprestimo = livroHasEmprestimo;
       this.descricaoAdvertencia = descricaoAdvertencia;
       this.dtAdvertencia = dtAdvertencia;
    }
   
    public int getCodigoAdvertencia() {
        return this.codigoAdvertencia;
    }
    
    public void setCodigoAdvertencia(int codigoAdvertencia) {
        this.codigoAdvertencia = codigoAdvertencia;
    }
    public LivroHasEmprestimo getLivroHasEmprestimo() {
        return this.livroHasEmprestimo;
    }
    
    public void setLivroHasEmprestimo(LivroHasEmprestimo livroHasEmprestimo) {
        this.livroHasEmprestimo = livroHasEmprestimo;
    }
    public String getDescricaoAdvertencia() {
        return this.descricaoAdvertencia;
    }
    
    public void setDescricaoAdvertencia(String descricaoAdvertencia) {
        this.descricaoAdvertencia = descricaoAdvertencia;
    }
    public Date getDtAdvertencia() {
        return this.dtAdvertencia;
    }
    
    public void setDtAdvertencia(Date dtAdvertencia) {
        this.dtAdvertencia = dtAdvertencia;
    }




}


