package models;
// Generated 20/11/2018 13:58:57 by Hibernate Tools 4.3.1



/**
 * AlunoId generated by hbm2java
 */
public class AlunoId  implements java.io.Serializable {


     private String matriculaAluno;
     private int pessoaCodigoPessoa;

    public AlunoId() {
    }

    public AlunoId(String matriculaAluno, int pessoaCodigoPessoa) {
       this.matriculaAluno = matriculaAluno;
       this.pessoaCodigoPessoa = pessoaCodigoPessoa;
    }
   
    public String getMatriculaAluno() {
        return this.matriculaAluno;
    }
    
    public void setMatriculaAluno(String matriculaAluno) {
        this.matriculaAluno = matriculaAluno;
    }
    public int getPessoaCodigoPessoa() {
        return this.pessoaCodigoPessoa;
    }
    
    public void setPessoaCodigoPessoa(int pessoaCodigoPessoa) {
        this.pessoaCodigoPessoa = pessoaCodigoPessoa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlunoId) ) return false;
		 AlunoId castOther = ( AlunoId ) other; 
         
		 return ( (this.getMatriculaAluno()==castOther.getMatriculaAluno()) || ( this.getMatriculaAluno()!=null && castOther.getMatriculaAluno()!=null && this.getMatriculaAluno().equals(castOther.getMatriculaAluno()) ) )
 && (this.getPessoaCodigoPessoa()==castOther.getPessoaCodigoPessoa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMatriculaAluno() == null ? 0 : this.getMatriculaAluno().hashCode() );
         result = 37 * result + this.getPessoaCodigoPessoa();
         return result;
   }   


}


