package models;
// Generated 20/11/2018 13:58:57 by Hibernate Tools 4.3.1



/**
 * Aluno generated by hbm2java
 */
public class Aluno  implements java.io.Serializable {


     private AlunoId id;
     private Modulo modulo;
     private Pessoa pessoa;

    public Aluno() {
    }

    public Aluno(AlunoId id, Modulo modulo, Pessoa pessoa) {
       this.id = id;
       this.modulo = modulo;
       this.pessoa = pessoa;
    }
   
    public AlunoId getId() {
        return this.id;
    }
    
    public void setId(AlunoId id) {
        this.id = id;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }




}


