package models;
// Generated 27/11/2018 14:35:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aluno generated by hbm2java
 */
public class Aluno  implements java.io.Serializable {


     private int idAluno;
     private Pessoa pessoa;
     private Set alunoHasCursos = new HashSet(0);

    public Aluno() {
    }

	
    public Aluno(int idAluno, Pessoa pessoa) {
        this.idAluno = idAluno;
        this.pessoa = pessoa;
    }
    public Aluno(int idAluno, Pessoa pessoa, Set alunoHasCursos) {
       this.idAluno = idAluno;
       this.pessoa = pessoa;
       this.alunoHasCursos = alunoHasCursos;
    }
   
    public int getIdAluno() {
        return this.idAluno;
    }
    
    public void setIdAluno(int idAluno) {
        this.idAluno = idAluno;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Set getAlunoHasCursos() {
        return this.alunoHasCursos;
    }
    
    public void setAlunoHasCursos(Set alunoHasCursos) {
        this.alunoHasCursos = alunoHasCursos;
    }




}


