package models;
// Generated 23/11/2018 17:35:30 by Hibernate Tools 4.3.1



/**
 * Aluno generated by hbm2java
 */
public class Aluno  implements java.io.Serializable {


     private int idAluno;
     private Modulo modulo;
     private Pessoa pessoa;

    public Aluno() {
    }

    public Aluno(int idAluno, Modulo modulo, Pessoa pessoa) {
       this.idAluno = idAluno;
       this.modulo = modulo;
       this.pessoa = pessoa;
    }
   
    public int getIdAluno() {
        return this.idAluno;
    }
    
    public void setIdAluno(int idAluno) {
        this.idAluno = idAluno;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }




}


