package models;
// Generated 20/11/2018 13:58:57 by Hibernate Tools 4.3.1



/**
 * Bibliotecaria generated by hbm2java
 */
public class Bibliotecaria  implements java.io.Serializable {


     private BibliotecariaId id;
     private Pessoa pessoa;
     private String senhaBibliotecaria;

    public Bibliotecaria() {
    }

    public Bibliotecaria(BibliotecariaId id, Pessoa pessoa, String senhaBibliotecaria) {
       this.id = id;
       this.pessoa = pessoa;
       this.senhaBibliotecaria = senhaBibliotecaria;
    }
   
    public BibliotecariaId getId() {
        return this.id;
    }
    
    public void setId(BibliotecariaId id) {
        this.id = id;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getSenhaBibliotecaria() {
        return this.senhaBibliotecaria;
    }
    
    public void setSenhaBibliotecaria(String senhaBibliotecaria) {
        this.senhaBibliotecaria = senhaBibliotecaria;
    }




}


