package models;
// Generated 27/11/2018 14:35:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.transaction.Transactional;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int idCurso;
     private Modulo modulo;
     private Turno turno;
     private String descricaoCurso;
     private Set professorHasCursos = new HashSet(0);
     private Set alunoHasCursos = new HashSet(0);

    public Curso() {
    }

	
    public Curso(int idCurso, Modulo modulo, Turno turno, String descricaoCurso) {
        this.idCurso = idCurso;
        this.modulo = modulo;
        this.turno = turno;
        this.descricaoCurso = descricaoCurso;
    }
    public Curso(int idCurso, Modulo modulo, Turno turno, String descricaoCurso, Set professorHasCursos, Set alunoHasCursos) {
       this.idCurso = idCurso;
       this.modulo = modulo;
       this.turno = turno;
       this.descricaoCurso = descricaoCurso;
       this.professorHasCursos = professorHasCursos;
       this.alunoHasCursos = alunoHasCursos;
    }
   
    public int getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public String getDescricaoCurso() {
        return this.descricaoCurso;
    }
    
    public void setDescricaoCurso(String descricaoCurso) {
        this.descricaoCurso = descricaoCurso;
    }
    public Set getProfessorHasCursos() {
        return this.professorHasCursos;
    }
    
    public void setProfessorHasCursos(Set professorHasCursos) {
        this.professorHasCursos = professorHasCursos;
    }
    public Set getAlunoHasCursos() {
        return this.alunoHasCursos;
    }
    
    public void setAlunoHasCursos(Set alunoHasCursos) {
        this.alunoHasCursos = alunoHasCursos;
    }

    @Override
    public String toString() {
        String valor = getDescricaoCurso() + "-" + getModulo().getDescricaoModulo() + "-" + getTurno().getDescricaoTurno();
        return valor; //To change body of generated methods, choose Tools | Templates.
    }
}


