package models;
// Generated 27/11/2018 14:35:48 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Emprestimo generated by hbm2java
 */
public class Emprestimo  implements java.io.Serializable {


     private int idEmprestimo;
     private Pessoa pessoa;
     private int quantidadeLivroEmprestimo;
     private Date dtSaidaEmprestimo;
     private Date dtDevolucaoEmprestimo;
     private String observacaoEmprestimo;
     private Set livroHasEmprestimos = new HashSet(0);

    public Emprestimo() {
    }

	
    public Emprestimo(int idEmprestimo, Pessoa pessoa, int quantidadeLivroEmprestimo, Date dtSaidaEmprestimo, Date dtDevolucaoEmprestimo, String observacaoEmprestimo) {
        this.idEmprestimo = idEmprestimo;
        this.pessoa = pessoa;
        this.quantidadeLivroEmprestimo = quantidadeLivroEmprestimo;
        this.dtSaidaEmprestimo = dtSaidaEmprestimo;
        this.dtDevolucaoEmprestimo = dtDevolucaoEmprestimo;
        this.observacaoEmprestimo = observacaoEmprestimo;
    }
    public Emprestimo(int idEmprestimo, Pessoa pessoa, int quantidadeLivroEmprestimo, Date dtSaidaEmprestimo, Date dtDevolucaoEmprestimo, String observacaoEmprestimo, Set livroHasEmprestimos) {
       this.idEmprestimo = idEmprestimo;
       this.pessoa = pessoa;
       this.quantidadeLivroEmprestimo = quantidadeLivroEmprestimo;
       this.dtSaidaEmprestimo = dtSaidaEmprestimo;
       this.dtDevolucaoEmprestimo = dtDevolucaoEmprestimo;
       this.observacaoEmprestimo = observacaoEmprestimo;
       this.livroHasEmprestimos = livroHasEmprestimos;
    }
   
    public int getIdEmprestimo() {
        return this.idEmprestimo;
    }
    
    public void setIdEmprestimo(int idEmprestimo) {
        this.idEmprestimo = idEmprestimo;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public int getQuantidadeLivroEmprestimo() {
        return this.quantidadeLivroEmprestimo;
    }
    
    public void setQuantidadeLivroEmprestimo(int quantidadeLivroEmprestimo) {
        this.quantidadeLivroEmprestimo = quantidadeLivroEmprestimo;
    }
    public Date getDtSaidaEmprestimo() {
        return this.dtSaidaEmprestimo;
    }
    
    public void setDtSaidaEmprestimo(Date dtSaidaEmprestimo) {
        this.dtSaidaEmprestimo = dtSaidaEmprestimo;
    }
    public Date getDtDevolucaoEmprestimo() {
        return this.dtDevolucaoEmprestimo;
    }
    
    public void setDtDevolucaoEmprestimo(Date dtDevolucaoEmprestimo) {
        this.dtDevolucaoEmprestimo = dtDevolucaoEmprestimo;
    }
    public String getObservacaoEmprestimo() {
        return this.observacaoEmprestimo;
    }
    
    public void setObservacaoEmprestimo(String observacaoEmprestimo) {
        this.observacaoEmprestimo = observacaoEmprestimo;
    }
    public Set getLivroHasEmprestimos() {
        return this.livroHasEmprestimos;
    }
    
    public void setLivroHasEmprestimos(Set livroHasEmprestimos) {
        this.livroHasEmprestimos = livroHasEmprestimos;
    }




}


