package models;
// Generated 20/11/2018 13:58:57 by Hibernate Tools 4.3.1



/**
 * EnderecoId generated by hbm2java
 */
public class EnderecoId  implements java.io.Serializable {


     private int cep;
     private int pessoaCodigoPessoa;

    public EnderecoId() {
    }

    public EnderecoId(int cep, int pessoaCodigoPessoa) {
       this.cep = cep;
       this.pessoaCodigoPessoa = pessoaCodigoPessoa;
    }
   
    public int getCep() {
        return this.cep;
    }
    
    public void setCep(int cep) {
        this.cep = cep;
    }
    public int getPessoaCodigoPessoa() {
        return this.pessoaCodigoPessoa;
    }
    
    public void setPessoaCodigoPessoa(int pessoaCodigoPessoa) {
        this.pessoaCodigoPessoa = pessoaCodigoPessoa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EnderecoId) ) return false;
		 EnderecoId castOther = ( EnderecoId ) other; 
         
		 return (this.getCep()==castOther.getCep())
 && (this.getPessoaCodigoPessoa()==castOther.getPessoaCodigoPessoa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCep();
         result = 37 * result + this.getPessoaCodigoPessoa();
         return result;
   }   


}


