package models;
// Generated 20/11/2018 13:58:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Exemplar generated by hbm2java
 */
public class Exemplar  implements java.io.Serializable {


     private String codigoExemplar;
     private Livro livro;
     private Set livroHasEmprestimos = new HashSet(0);

    public Exemplar() {
    }

	
    public Exemplar(String codigoExemplar, Livro livro) {
        this.codigoExemplar = codigoExemplar;
        this.livro = livro;
    }
    public Exemplar(String codigoExemplar, Livro livro, Set livroHasEmprestimos) {
       this.codigoExemplar = codigoExemplar;
       this.livro = livro;
       this.livroHasEmprestimos = livroHasEmprestimos;
    }
   
    public String getCodigoExemplar() {
        return this.codigoExemplar;
    }
    
    public void setCodigoExemplar(String codigoExemplar) {
        this.codigoExemplar = codigoExemplar;
    }
    public Livro getLivro() {
        return this.livro;
    }
    
    public void setLivro(Livro livro) {
        this.livro = livro;
    }
    public Set getLivroHasEmprestimos() {
        return this.livroHasEmprestimos;
    }
    
    public void setLivroHasEmprestimos(Set livroHasEmprestimos) {
        this.livroHasEmprestimos = livroHasEmprestimos;
    }




}


