package models;
// Generated 20/11/2018 13:58:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LivroHasEmprestimo generated by hbm2java
 */
public class LivroHasEmprestimo  implements java.io.Serializable {


     private int codigoLivroEmprestimo;
     private Emprestimo emprestimo;
     private Exemplar exemplar;
     private Set advertencias = new HashSet(0);

    public LivroHasEmprestimo() {
    }

	
    public LivroHasEmprestimo(int codigoLivroEmprestimo, Emprestimo emprestimo, Exemplar exemplar) {
        this.codigoLivroEmprestimo = codigoLivroEmprestimo;
        this.emprestimo = emprestimo;
        this.exemplar = exemplar;
    }
    public LivroHasEmprestimo(int codigoLivroEmprestimo, Emprestimo emprestimo, Exemplar exemplar, Set advertencias) {
       this.codigoLivroEmprestimo = codigoLivroEmprestimo;
       this.emprestimo = emprestimo;
       this.exemplar = exemplar;
       this.advertencias = advertencias;
    }
   
    public int getCodigoLivroEmprestimo() {
        return this.codigoLivroEmprestimo;
    }
    
    public void setCodigoLivroEmprestimo(int codigoLivroEmprestimo) {
        this.codigoLivroEmprestimo = codigoLivroEmprestimo;
    }
    public Emprestimo getEmprestimo() {
        return this.emprestimo;
    }
    
    public void setEmprestimo(Emprestimo emprestimo) {
        this.emprestimo = emprestimo;
    }
    public Exemplar getExemplar() {
        return this.exemplar;
    }
    
    public void setExemplar(Exemplar exemplar) {
        this.exemplar = exemplar;
    }
    public Set getAdvertencias() {
        return this.advertencias;
    }
    
    public void setAdvertencias(Set advertencias) {
        this.advertencias = advertencias;
    }




}


