package models;
// Generated 20/11/2018 13:58:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Livro generated by hbm2java
 */
public class Livro  implements java.io.Serializable {


     private int cddLivro;
     private String tituloLivro;
     private String subTituloLivro;
     private String autorLivro;
     private String editoraLivro;
     private String edicaoLivro;
     private int serieLivro;
     private String anoLivro;
     private int paginas;
     private String assunto;
     private String isbn;
     private String idioma;
     private Set exemplars = new HashSet(0);

    public Livro() {
    }

	
    public Livro(int cddLivro, String tituloLivro, String subTituloLivro, String autorLivro, String editoraLivro, String edicaoLivro, int serieLivro, String anoLivro, int paginas, String assunto, String isbn, String idioma) {
        this.cddLivro = cddLivro;
        this.tituloLivro = tituloLivro;
        this.subTituloLivro = subTituloLivro;
        this.autorLivro = autorLivro;
        this.editoraLivro = editoraLivro;
        this.edicaoLivro = edicaoLivro;
        this.serieLivro = serieLivro;
        this.anoLivro = anoLivro;
        this.paginas = paginas;
        this.assunto = assunto;
        this.isbn = isbn;
        this.idioma = idioma;
    }
    public Livro(int cddLivro, String tituloLivro, String subTituloLivro, String autorLivro, String editoraLivro, String edicaoLivro, int serieLivro, String anoLivro, int paginas, String assunto, String isbn, String idioma, Set exemplars) {
       this.cddLivro = cddLivro;
       this.tituloLivro = tituloLivro;
       this.subTituloLivro = subTituloLivro;
       this.autorLivro = autorLivro;
       this.editoraLivro = editoraLivro;
       this.edicaoLivro = edicaoLivro;
       this.serieLivro = serieLivro;
       this.anoLivro = anoLivro;
       this.paginas = paginas;
       this.assunto = assunto;
       this.isbn = isbn;
       this.idioma = idioma;
       this.exemplars = exemplars;
    }
   
    public int getCddLivro() {
        return this.cddLivro;
    }
    
    public void setCddLivro(int cddLivro) {
        this.cddLivro = cddLivro;
    }
    public String getTituloLivro() {
        return this.tituloLivro;
    }
    
    public void setTituloLivro(String tituloLivro) {
        this.tituloLivro = tituloLivro;
    }
    public String getSubTituloLivro() {
        return this.subTituloLivro;
    }
    
    public void setSubTituloLivro(String subTituloLivro) {
        this.subTituloLivro = subTituloLivro;
    }
    public String getAutorLivro() {
        return this.autorLivro;
    }
    
    public void setAutorLivro(String autorLivro) {
        this.autorLivro = autorLivro;
    }
    public String getEditoraLivro() {
        return this.editoraLivro;
    }
    
    public void setEditoraLivro(String editoraLivro) {
        this.editoraLivro = editoraLivro;
    }
    public String getEdicaoLivro() {
        return this.edicaoLivro;
    }
    
    public void setEdicaoLivro(String edicaoLivro) {
        this.edicaoLivro = edicaoLivro;
    }
    public int getSerieLivro() {
        return this.serieLivro;
    }
    
    public void setSerieLivro(int serieLivro) {
        this.serieLivro = serieLivro;
    }
    public String getAnoLivro() {
        return this.anoLivro;
    }
    
    public void setAnoLivro(String anoLivro) {
        this.anoLivro = anoLivro;
    }
    public int getPaginas() {
        return this.paginas;
    }
    
    public void setPaginas(int paginas) {
        this.paginas = paginas;
    }
    public String getAssunto() {
        return this.assunto;
    }
    
    public void setAssunto(String assunto) {
        this.assunto = assunto;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(String idioma) {
        this.idioma = idioma;
    }
    public Set getExemplars() {
        return this.exemplars;
    }
    
    public void setExemplars(Set exemplars) {
        this.exemplars = exemplars;
    }




}


