package models;
// Generated 27/11/2018 14:35:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modulo generated by hbm2java
 */
public class Modulo  implements java.io.Serializable {


     private int idModulo;
     private String descricaoModulo;
     private Set cursos = new HashSet(0);

    public Modulo() {
    }

	
    public Modulo(int idModulo, String descricaoModulo) {
        this.idModulo = idModulo;
        this.descricaoModulo = descricaoModulo;
    }
    public Modulo(int idModulo, String descricaoModulo, Set cursos) {
       this.idModulo = idModulo;
       this.descricaoModulo = descricaoModulo;
       this.cursos = cursos;
    }
   
    public int getIdModulo() {
        return this.idModulo;
    }
    
    public void setIdModulo(int idModulo) {
        this.idModulo = idModulo;
    }
    public String getDescricaoModulo() {
        return this.descricaoModulo;
    }
    
    public void setDescricaoModulo(String descricaoModulo) {
        this.descricaoModulo = descricaoModulo;
    }
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


