package models;
// Generated 20/11/2018 13:58:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modulo generated by hbm2java
 */
public class Modulo  implements java.io.Serializable {


     private int codigoModulo;
     private Turno turno;
     private String descricaoModulo;
     private Set alunos = new HashSet(0);

    public Modulo() {
    }

	
    public Modulo(int codigoModulo, Turno turno, String descricaoModulo) {
        this.codigoModulo = codigoModulo;
        this.turno = turno;
        this.descricaoModulo = descricaoModulo;
    }
    public Modulo(int codigoModulo, Turno turno, String descricaoModulo, Set alunos) {
       this.codigoModulo = codigoModulo;
       this.turno = turno;
       this.descricaoModulo = descricaoModulo;
       this.alunos = alunos;
    }
   
    public int getCodigoModulo() {
        return this.codigoModulo;
    }
    
    public void setCodigoModulo(int codigoModulo) {
        this.codigoModulo = codigoModulo;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public String getDescricaoModulo() {
        return this.descricaoModulo;
    }
    
    public void setDescricaoModulo(String descricaoModulo) {
        this.descricaoModulo = descricaoModulo;
    }
    public Set getAlunos() {
        return this.alunos;
    }
    
    public void setAlunos(Set alunos) {
        this.alunos = alunos;
    }




}


