package models;
// Generated 23/11/2018 17:35:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modulo generated by hbm2java
 */
public class Modulo  implements java.io.Serializable {


     private int idModulo;
     private Turno turno;
     private String descricaoModulo;
     private Set alunos = new HashSet(0);

    public Modulo() {
    }

	
    public Modulo(int idModulo, Turno turno, String descricaoModulo) {
        this.idModulo = idModulo;
        this.turno = turno;
        this.descricaoModulo = descricaoModulo;
    }
    public Modulo(int idModulo, Turno turno, String descricaoModulo, Set alunos) {
       this.idModulo = idModulo;
       this.turno = turno;
       this.descricaoModulo = descricaoModulo;
       this.alunos = alunos;
    }
   
    public int getIdModulo() {
        return this.idModulo;
    }
    
    public void setIdModulo(int idModulo) {
        this.idModulo = idModulo;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public String getDescricaoModulo() {
        return this.descricaoModulo;
    }
    
    public void setDescricaoModulo(String descricaoModulo) {
        this.descricaoModulo = descricaoModulo;
    }
    public Set getAlunos() {
        return this.alunos;
    }
    
    public void setAlunos(Set alunos) {
        this.alunos = alunos;
    }




}


