package models;
// Generated 20/11/2018 13:58:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Professor generated by hbm2java
 */
public class Professor  implements java.io.Serializable {


     private String numeroFuncionalProfessor;
     private Pessoa pessoa;
     private Set professorHasCursos = new HashSet(0);

    public Professor() {
    }

	
    public Professor(String numeroFuncionalProfessor, Pessoa pessoa) {
        this.numeroFuncionalProfessor = numeroFuncionalProfessor;
        this.pessoa = pessoa;
    }
    public Professor(String numeroFuncionalProfessor, Pessoa pessoa, Set professorHasCursos) {
       this.numeroFuncionalProfessor = numeroFuncionalProfessor;
       this.pessoa = pessoa;
       this.professorHasCursos = professorHasCursos;
    }
   
    public String getNumeroFuncionalProfessor() {
        return this.numeroFuncionalProfessor;
    }
    
    public void setNumeroFuncionalProfessor(String numeroFuncionalProfessor) {
        this.numeroFuncionalProfessor = numeroFuncionalProfessor;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Set getProfessorHasCursos() {
        return this.professorHasCursos;
    }
    
    public void setProfessorHasCursos(Set professorHasCursos) {
        this.professorHasCursos = professorHasCursos;
    }




}


