package models;
// Generated 20/11/2018 13:58:57 by Hibernate Tools 4.3.1



/**
 * ProfessorHasCurso generated by hbm2java
 */
public class ProfessorHasCurso  implements java.io.Serializable {


     private int codigoProfessorHasCurso;
     private Curso curso;
     private Professor professor;

    public ProfessorHasCurso() {
    }

    public ProfessorHasCurso(int codigoProfessorHasCurso, Curso curso, Professor professor) {
       this.codigoProfessorHasCurso = codigoProfessorHasCurso;
       this.curso = curso;
       this.professor = professor;
    }
   
    public int getCodigoProfessorHasCurso() {
        return this.codigoProfessorHasCurso;
    }
    
    public void setCodigoProfessorHasCurso(int codigoProfessorHasCurso) {
        this.codigoProfessorHasCurso = codigoProfessorHasCurso;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Professor getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Professor professor) {
        this.professor = professor;
    }




}


