package models;
// Generated 27/11/2018 14:35:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Turno generated by hbm2java
 */
public class Turno  implements java.io.Serializable {


     private int idTurno;
     private String descricaoTurno;
     private Set cursos = new HashSet(0);

    public Turno() {
    }

	
    public Turno(int idTurno, String descricaoTurno) {
        this.idTurno = idTurno;
        this.descricaoTurno = descricaoTurno;
    }
    public Turno(int idTurno, String descricaoTurno, Set cursos) {
       this.idTurno = idTurno;
       this.descricaoTurno = descricaoTurno;
       this.cursos = cursos;
    }
   
    public int getIdTurno() {
        return this.idTurno;
    }
    
    public void setIdTurno(int idTurno) {
        this.idTurno = idTurno;
    }
    public String getDescricaoTurno() {
        return this.descricaoTurno;
    }
    
    public void setDescricaoTurno(String descricaoTurno) {
        this.descricaoTurno = descricaoTurno;
    }
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


